// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package store

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRateEvent = `-- name: AddRateEvent :exec
INSERT INTO rate_events (key) VALUES ($1)
`

func (q *Queries) AddRateEvent(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, addRateEvent, key)
	return err
}

const countEmailCodeAttempt = `-- name: CountEmailCodeAttempt :exec
UPDATE email_codes SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) CountEmailCodeAttempt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, countEmailCodeAttempt, id)
	return err
}

const countRateEvents = `-- name: CountRateEvents :one
SELECT count(*) FROM rate_events WHERE key = $1 AND at > now() - make_interval(secs => $2::float8)
`

type CountRateEventsParams struct {
	Key        string
	WindowSecs float64
}

func (q *Queries) CountRateEvents(ctx context.Context, arg CountRateEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRateEvents, arg.Key, arg.WindowSecs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailCode = `-- name: CreateEmailCode :exec
INSERT INTO email_codes (email, code_hash, link_token_hash, expires_at, purpose) VALUES ($1, $2, $3, $4, $5)
`

type CreateEmailCodeParams struct {
	Email         string
	CodeHash      []byte
	LinkTokenHash []byte
	ExpiresAt     pgtype.Timestamptz
	Purpose       string
}

func (q *Queries) CreateEmailCode(ctx context.Context, arg CreateEmailCodeParams) error {
	_, err := q.db.Exec(ctx, createEmailCode,
		arg.Email,
		arg.CodeHash,
		arg.LinkTokenHash,
		arg.ExpiresAt,
		arg.Purpose,
	)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at, ip, user_agent, reauth_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, token_hash, created_at, last_seen_at, expires_at, reauth_at, ip, user_agent, revoked_at
`

type CreateSessionParams struct {
	UserID    pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	Ip        *netip.Addr
	UserAgent string
	ReauthAt  pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
		arg.ReauthAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.ReauthAt,
		&i.Ip,
		&i.UserAgent,
		&i.RevokedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, email_verified_at) VALUES ($1, now()) RETURNING id, email, email_verified_at, name, created_at, webauthn_handle, totp_secret, totp_enabled_at, totp_last_step, sftp_username, theme
`

func (q *Queries) CreateUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Name,
		&i.CreatedAt,
		&i.WebauthnHandle,
		&i.TotpSecret,
		&i.TotpEnabledAt,
		&i.TotpLastStep,
		&i.SftpUsername,
		&i.Theme,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserActivity = `-- name: DeleteUserActivity :exec
DELETE FROM audit_log WHERE user_id = $1 AND org_id IS NULL
`

// An account's own events go with it; its orgs' events stay.
func (q *Queries) DeleteUserActivity(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserActivity, userID)
	return err
}

const emailCodeByLink = `-- name: EmailCodeByLink :one
SELECT id, email, code_hash, link_token_hash, purpose, attempts, expires_at, used_at, created_at FROM email_codes WHERE link_token_hash = $1 AND purpose = 'signin' FOR UPDATE
`

// Only sign-in emails have links.
func (q *Queries) EmailCodeByLink(ctx context.Context, linkTokenHash []byte) (EmailCode, error) {
	row := q.db.QueryRow(ctx, emailCodeByLink, linkTokenHash)
	var i EmailCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.LinkTokenHash,
		&i.Purpose,
		&i.Attempts,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, token_hash, created_at, last_seen_at, expires_at, reauth_at, ip, user_agent, revoked_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.ReauthAt,
		&i.Ip,
		&i.UserAgent,
		&i.RevokedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, email_verified_at, name, created_at, webauthn_handle, totp_secret, totp_enabled_at, totp_last_step, sftp_username, theme FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Name,
		&i.CreatedAt,
		&i.WebauthnHandle,
		&i.TotpSecret,
		&i.TotpEnabledAt,
		&i.TotpLastStep,
		&i.SftpUsername,
		&i.Theme,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_verified_at, name, created_at, webauthn_handle, totp_secret, totp_enabled_at, totp_last_step, sftp_username, theme FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Name,
		&i.CreatedAt,
		&i.WebauthnHandle,
		&i.TotpSecret,
		&i.TotpEnabledAt,
		&i.TotpLastStep,
		&i.SftpUsername,
		&i.Theme,
	)
	return i, err
}

const latestEmailCode = `-- name: LatestEmailCode :one
SELECT id, email, code_hash, link_token_hash, purpose, attempts, expires_at, used_at, created_at FROM email_codes WHERE email = $1 AND purpose = $2 AND used_at IS NULL
ORDER BY created_at DESC LIMIT 1
FOR UPDATE
`

type LatestEmailCodeParams struct {
	Email   string
	Purpose string
}

// The newest unused code for an address and purpose, locked for checking.
func (q *Queries) LatestEmailCode(ctx context.Context, arg LatestEmailCodeParams) (EmailCode, error) {
	row := q.db.QueryRow(ctx, latestEmailCode, arg.Email, arg.Purpose)
	var i EmailCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.LinkTokenHash,
		&i.Purpose,
		&i.Attempts,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, user_id, token_hash, created_at, last_seen_at, expires_at, reauth_at, ip, user_agent, revoked_at FROM sessions
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > now()
ORDER BY last_seen_at DESC
`

func (q *Queries) ListUserSessions(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.ReauthAt,
			&i.Ip,
			&i.UserAgent,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneEmailCodes = `-- name: PruneEmailCodes :exec
DELETE FROM email_codes WHERE expires_at < now() - interval '1 day'
`

func (q *Queries) PruneEmailCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneEmailCodes)
	return err
}

const pruneRateEvents = `-- name: PruneRateEvents :exec
DELETE FROM rate_events WHERE at < now() - interval '1 day'
`

func (q *Queries) PruneRateEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneRateEvents)
	return err
}

const pruneSessions = `-- name: PruneSessions :exec
DELETE FROM sessions WHERE expires_at < now() - interval '30 days' OR revoked_at < now() - interval '30 days'
`

func (q *Queries) PruneSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneSessions)
	return err
}

const revokeOtherSessions = `-- name: RevokeOtherSessions :exec
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND id <> $2 AND revoked_at IS NULL
`

type RevokeOtherSessionsParams struct {
	UserID pgtype.UUID
	ID     pgtype.UUID
}

func (q *Queries) RevokeOtherSessions(ctx context.Context, arg RevokeOtherSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeOtherSessions, arg.UserID, arg.ID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.UserID)
	return err
}

const revokeSessionByToken = `-- name: RevokeSessionByToken :exec
UPDATE sessions SET revoked_at = now() WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSessionByToken, tokenHash)
	return err
}

const sessionByToken = `-- name: SessionByToken :one
SELECT id, user_id, token_hash, created_at, last_seen_at, expires_at, reauth_at, ip, user_agent, revoked_at FROM sessions WHERE token_hash = $1
`

func (q *Queries) SessionByToken(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, sessionByToken, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.ReauthAt,
		&i.Ip,
		&i.UserAgent,
		&i.RevokedAt,
	)
	return i, err
}

const setSessionReauth = `-- name: SetSessionReauth :exec
UPDATE sessions SET reauth_at = $2 WHERE id = $1
`

type SetSessionReauthParams struct {
	ID       pgtype.UUID
	ReauthAt pgtype.Timestamptz
}

func (q *Queries) SetSessionReauth(ctx context.Context, arg SetSessionReauthParams) error {
	_, err := q.db.Exec(ctx, setSessionReauth, arg.ID, arg.ReauthAt)
	return err
}

const setUserEmail = `-- name: SetUserEmail :one
UPDATE users SET email = $2, email_verified_at = now() WHERE id = $1 RETURNING id, email, email_verified_at, name, created_at, webauthn_handle, totp_secret, totp_enabled_at, totp_last_step, sftp_username, theme
`

type SetUserEmailParams struct {
	ID    pgtype.UUID
	Email string
}

func (q *Queries) SetUserEmail(ctx context.Context, arg SetUserEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserEmail, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Name,
		&i.CreatedAt,
		&i.WebauthnHandle,
		&i.TotpSecret,
		&i.TotpEnabledAt,
		&i.TotpLastStep,
		&i.SftpUsername,
		&i.Theme,
	)
	return i, err
}

const setUserName = `-- name: SetUserName :one
UPDATE users SET name = $2 WHERE id = $1 RETURNING id, email, email_verified_at, name, created_at, webauthn_handle, totp_secret, totp_enabled_at, totp_last_step, sftp_username, theme
`

type SetUserNameParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) SetUserName(ctx context.Context, arg SetUserNameParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserName, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Name,
		&i.CreatedAt,
		&i.WebauthnHandle,
		&i.TotpSecret,
		&i.TotpEnabledAt,
		&i.TotpLastStep,
		&i.SftpUsername,
		&i.Theme,
	)
	return i, err
}

const setUserTheme = `-- name: SetUserTheme :one
UPDATE users SET theme = $2 WHERE id = $1 RETURNING id, email, email_verified_at, name, created_at, webauthn_handle, totp_secret, totp_enabled_at, totp_last_step, sftp_username, theme
`

type SetUserThemeParams struct {
	ID    pgtype.UUID
	Theme string
}

func (q *Queries) SetUserTheme(ctx context.Context, arg SetUserThemeParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserTheme, arg.ID, arg.Theme)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Name,
		&i.CreatedAt,
		&i.WebauthnHandle,
		&i.TotpSecret,
		&i.TotpEnabledAt,
		&i.TotpLastStep,
		&i.SftpUsername,
		&i.Theme,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const useEmailCode = `-- name: UseEmailCode :exec
UPDATE email_codes SET used_at = now() WHERE id = $1
`

func (q *Queries) UseEmailCode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, useEmailCode, id)
	return err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users SET email_verified_at = now() WHERE id = $1 AND email_verified_at IS NULL
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, id)
	return err
}
