// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package store

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAuditEvent = `-- name: AddAuditEvent :exec
INSERT INTO audit_log (org_id, user_id, actor, actor_id, action, target, ip, user_agent, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type AddAuditEventParams struct {
	OrgID     pgtype.UUID
	UserID    pgtype.UUID
	Actor     string
	ActorID   pgtype.UUID
	Action    string
	Target    string
	Ip        *netip.Addr
	UserAgent string
	Metadata  []byte
}

func (q *Queries) AddAuditEvent(ctx context.Context, arg AddAuditEventParams) error {
	_, err := q.db.Exec(ctx, addAuditEvent,
		arg.OrgID,
		arg.UserID,
		arg.Actor,
		arg.ActorID,
		arg.Action,
		arg.Target,
		arg.Ip,
		arg.UserAgent,
		arg.Metadata,
	)
	return err
}

const orgAuditLog = `-- name: OrgAuditLog :many
SELECT a.id, a.org_id, a.user_id, a.actor, a.actor_id, a.action, a.target, a.ip, a.user_agent, a.metadata, a.at, u.email AS actor_email FROM audit_log a
LEFT JOIN users u ON u.id = a.actor_id
WHERE a.org_id = $1 AND ($2::uuid IS NULL OR a.id < $2::uuid)
ORDER BY a.id DESC
LIMIT $3
`

type OrgAuditLogParams struct {
	OrgID  pgtype.UUID
	Before pgtype.UUID
	Lim    int32
}

type OrgAuditLogRow struct {
	ID         pgtype.UUID
	OrgID      pgtype.UUID
	UserID     pgtype.UUID
	Actor      string
	ActorID    pgtype.UUID
	Action     string
	Target     string
	Ip         *netip.Addr
	UserAgent  string
	Metadata   []byte
	At         pgtype.Timestamptz
	ActorEmail pgtype.Text
}

func (q *Queries) OrgAuditLog(ctx context.Context, arg OrgAuditLogParams) ([]OrgAuditLogRow, error) {
	rows, err := q.db.Query(ctx, orgAuditLog, arg.OrgID, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgAuditLogRow
	for rows.Next() {
		var i OrgAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Actor,
			&i.ActorID,
			&i.Action,
			&i.Target,
			&i.Ip,
			&i.UserAgent,
			&i.Metadata,
			&i.At,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAuditLog = `-- name: PruneAuditLog :exec
DELETE FROM audit_log WHERE at < now() - interval '1 year'
`

func (q *Queries) PruneAuditLog(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneAuditLog)
	return err
}

const serverAuditLog = `-- name: ServerAuditLog :many
SELECT a.id, a.org_id, a.user_id, a.actor, a.actor_id, a.action, a.target, a.ip, a.user_agent, a.metadata, a.at, u.email AS actor_email FROM audit_log a
LEFT JOIN users u ON u.id = a.actor_id
WHERE a.org_id = $1 AND a.action = 'command' AND a.target = $2::text
  AND a.metadata->>'node' = $3::text
  AND ($4::uuid IS NULL OR a.id < $4::uuid)
ORDER BY a.id DESC
LIMIT $5
`

type ServerAuditLogParams struct {
	OrgID    pgtype.UUID
	ServerID string
	NodeID   string
	Before   pgtype.UUID
	Lim      int32
}

type ServerAuditLogRow struct {
	ID         pgtype.UUID
	OrgID      pgtype.UUID
	UserID     pgtype.UUID
	Actor      string
	ActorID    pgtype.UUID
	Action     string
	Target     string
	Ip         *netip.Addr
	UserAgent  string
	Metadata   []byte
	At         pgtype.Timestamptz
	ActorEmail pgtype.Text
}

// The commands sent to one server, newest first.
func (q *Queries) ServerAuditLog(ctx context.Context, arg ServerAuditLogParams) ([]ServerAuditLogRow, error) {
	rows, err := q.db.Query(ctx, serverAuditLog,
		arg.OrgID,
		arg.ServerID,
		arg.NodeID,
		arg.Before,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServerAuditLogRow
	for rows.Next() {
		var i ServerAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Actor,
			&i.ActorID,
			&i.Action,
			&i.Target,
			&i.Ip,
			&i.UserAgent,
			&i.Metadata,
			&i.At,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionsWithUserAgent = `-- name: SessionsWithUserAgent :one
SELECT count(*) AS total, count(*) FILTER (WHERE user_agent = $1) AS same
FROM sessions WHERE user_id = $2
`

type SessionsWithUserAgentParams struct {
	UserAgent string
	UserID    pgtype.UUID
}

type SessionsWithUserAgentRow struct {
	Total int64
	Same  int64
}

// For new-device emails: the user's sessions so far, and those from this
// browser.
func (q *Queries) SessionsWithUserAgent(ctx context.Context, arg SessionsWithUserAgentParams) (SessionsWithUserAgentRow, error) {
	row := q.db.QueryRow(ctx, sessionsWithUserAgent, arg.UserAgent, arg.UserID)
	var i SessionsWithUserAgentRow
	err := row.Scan(&i.Total, &i.Same)
	return i, err
}

const userActivity = `-- name: UserActivity :many
SELECT id, org_id, user_id, actor, actor_id, action, target, ip, user_agent, metadata, at FROM audit_log
WHERE user_id = $1 AND org_id IS NULL AND ($2::uuid IS NULL OR id < $2::uuid)
ORDER BY id DESC
LIMIT $3
`

type UserActivityParams struct {
	UserID pgtype.UUID
	Before pgtype.UUID
	Lim    int32
}

// An account's own events, newest first, before a cursor (an event ID).
func (q *Queries) UserActivity(ctx context.Context, arg UserActivityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, userActivity, arg.UserID, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Actor,
			&i.ActorID,
			&i.Action,
			&i.Target,
			&i.Ip,
			&i.UserAgent,
			&i.Metadata,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
