// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backup_storage.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeBackupStorage = `-- name: ActiveBackupStorage :one
SELECT id, org_id, node_id, key_id, enabled_at, enabled_by, disabled_at, purged_at FROM backup_storage WHERE node_id = $1 AND disabled_at IS NULL
`

func (q *Queries) ActiveBackupStorage(ctx context.Context, nodeID pgtype.UUID) (BackupStorage, error) {
	row := q.db.QueryRow(ctx, activeBackupStorage, nodeID)
	var i BackupStorage
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.NodeID,
		&i.KeyID,
		&i.EnabledAt,
		&i.EnabledBy,
		&i.DisabledAt,
		&i.PurgedAt,
	)
	return i, err
}

const backupStorageOrgsToMeasure = `-- name: BackupStorageOrgsToMeasure :many
SELECT DISTINCT s.org_id FROM backup_storage s
WHERE s.purged_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM backup_storage_usage u WHERE u.org_id = s.org_id AND u.day = $1)
`

// Orgs with storage on, or data not deleted yet, not measured on day.
func (q *Queries) BackupStorageOrgsToMeasure(ctx context.Context, day pgtype.Date) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, backupStorageOrgsToMeasure, day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var org_id pgtype.UUID
		if err := rows.Scan(&org_id); err != nil {
			return nil, err
		}
		items = append(items, org_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backupStorageToPurge = `-- name: BackupStorageToPurge :many
SELECT id, org_id, node_id, key_id, enabled_at, enabled_by, disabled_at, purged_at FROM backup_storage WHERE purged_at IS NULL AND disabled_at < $1
`

// Turned off over 30 days ago, data not deleted yet.
func (q *Queries) BackupStorageToPurge(ctx context.Context, before pgtype.Timestamptz) ([]BackupStorage, error) {
	rows, err := q.db.Query(ctx, backupStorageToPurge, before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BackupStorage
	for rows.Next() {
		var i BackupStorage
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.NodeID,
			&i.KeyID,
			&i.EnabledAt,
			&i.EnabledBy,
			&i.DisabledAt,
			&i.PurgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const disableBackupStorage = `-- name: DisableBackupStorage :one
UPDATE backup_storage SET disabled_at = now() WHERE node_id = $1 AND disabled_at IS NULL RETURNING id, org_id, node_id, key_id, enabled_at, enabled_by, disabled_at, purged_at
`

func (q *Queries) DisableBackupStorage(ctx context.Context, nodeID pgtype.UUID) (BackupStorage, error) {
	row := q.db.QueryRow(ctx, disableBackupStorage, nodeID)
	var i BackupStorage
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.NodeID,
		&i.KeyID,
		&i.EnabledAt,
		&i.EnabledBy,
		&i.DisabledAt,
		&i.PurgedAt,
	)
	return i, err
}

const insertBackupStorage = `-- name: InsertBackupStorage :one
INSERT INTO backup_storage (org_id, node_id, key_id, enabled_by) VALUES ($1, $2, $3, $4) RETURNING id, org_id, node_id, key_id, enabled_at, enabled_by, disabled_at, purged_at
`

type InsertBackupStorageParams struct {
	OrgID     pgtype.UUID
	NodeID    pgtype.UUID
	KeyID     string
	EnabledBy pgtype.UUID
}

func (q *Queries) InsertBackupStorage(ctx context.Context, arg InsertBackupStorageParams) (BackupStorage, error) {
	row := q.db.QueryRow(ctx, insertBackupStorage,
		arg.OrgID,
		arg.NodeID,
		arg.KeyID,
		arg.EnabledBy,
	)
	var i BackupStorage
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.NodeID,
		&i.KeyID,
		&i.EnabledAt,
		&i.EnabledBy,
		&i.DisabledAt,
		&i.PurgedAt,
	)
	return i, err
}

const insertBackupStorageUsage = `-- name: InsertBackupStorageUsage :exec
INSERT INTO backup_storage_usage (org_id, day, bytes) VALUES ($1, $2, $3)
ON CONFLICT (org_id, day) DO UPDATE SET bytes = excluded.bytes, measured_at = now()
`

type InsertBackupStorageUsageParams struct {
	OrgID pgtype.UUID
	Day   pgtype.Date
	Bytes int64
}

func (q *Queries) InsertBackupStorageUsage(ctx context.Context, arg InsertBackupStorageUsageParams) error {
	_, err := q.db.Exec(ctx, insertBackupStorageUsage, arg.OrgID, arg.Day, arg.Bytes)
	return err
}

const latestBackupStorageUsage = `-- name: LatestBackupStorageUsage :one
SELECT org_id, day, bytes, measured_at FROM backup_storage_usage WHERE org_id = $1 ORDER BY day DESC LIMIT 1
`

func (q *Queries) LatestBackupStorageUsage(ctx context.Context, orgID pgtype.UUID) (BackupStorageUsage, error) {
	row := q.db.QueryRow(ctx, latestBackupStorageUsage, orgID)
	var i BackupStorageUsage
	err := row.Scan(
		&i.OrgID,
		&i.Day,
		&i.Bytes,
		&i.MeasuredAt,
	)
	return i, err
}

const orgBackupStorage = `-- name: OrgBackupStorage :many
SELECT id, org_id, node_id, key_id, enabled_at, enabled_by, disabled_at, purged_at FROM backup_storage WHERE org_id = $1 AND disabled_at IS NULL
`

func (q *Queries) OrgBackupStorage(ctx context.Context, orgID pgtype.UUID) ([]BackupStorage, error) {
	rows, err := q.db.Query(ctx, orgBackupStorage, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BackupStorage
	for rows.Next() {
		var i BackupStorage
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.NodeID,
			&i.KeyID,
			&i.EnabledAt,
			&i.EnabledBy,
			&i.DisabledAt,
			&i.PurgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBackupStoragePurged = `-- name: SetBackupStoragePurged :exec
UPDATE backup_storage SET purged_at = now() WHERE id = $1
`

func (q *Queries) SetBackupStoragePurged(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setBackupStoragePurged, id)
	return err
}
