// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backup_keys.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBackupKey = `-- name: DeleteBackupKey :exec
DELETE FROM backup_keys WHERE node_id = $1
`

func (q *Queries) DeleteBackupKey(ctx context.Context, nodeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBackupKey, nodeID)
	return err
}

const getBackupKey = `-- name: GetBackupKey :one
SELECT node_id, org_id, sealed, fingerprint, stored_at FROM backup_keys WHERE node_id = $1
`

func (q *Queries) GetBackupKey(ctx context.Context, nodeID pgtype.UUID) (BackupKey, error) {
	row := q.db.QueryRow(ctx, getBackupKey, nodeID)
	var i BackupKey
	err := row.Scan(
		&i.NodeID,
		&i.OrgID,
		&i.Sealed,
		&i.Fingerprint,
		&i.StoredAt,
	)
	return i, err
}

const nodesWithoutBackupKey = `-- name: NodesWithoutBackupKey :many
SELECT n.id, n.org_id FROM nodes n
WHERE n.deleted_at IS NULL AND n.org_id IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM backup_keys k WHERE k.node_id = n.id)
`

type NodesWithoutBackupKeyRow struct {
	ID    pgtype.UUID
	OrgID pgtype.UUID
}

// Linked nodes whose key the Panel hasn't asked for yet.
func (q *Queries) NodesWithoutBackupKey(ctx context.Context) ([]NodesWithoutBackupKeyRow, error) {
	rows, err := q.db.Query(ctx, nodesWithoutBackupKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodesWithoutBackupKeyRow
	for rows.Next() {
		var i NodesWithoutBackupKeyRow
		if err := rows.Scan(&i.ID, &i.OrgID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoverySources = `-- name: RecoverySources :many
SELECT n.id, n.name, n.deleted_at,
       EXISTS (SELECT 1 FROM backup_keys k WHERE k.node_id = n.id) AS key_kept,
       EXISTS (SELECT 1 FROM backup_storage s WHERE s.node_id = n.id AND s.purged_at IS NULL) AS has_storage
FROM nodes n
WHERE n.org_id = $1
ORDER BY n.deleted_at IS NOT NULL, n.name
`

type RecoverySourcesRow struct {
	ID         pgtype.UUID
	Name       string
	DeletedAt  pgtype.Timestamptz
	KeyKept    bool
	HasStorage bool
}

// The org's nodes, removed ones included, with what's there to recover
// their backups with: the Panel's copy of their key, and whether they had
// Raptor Backup Storage (whose files aren't deleted yet).
func (q *Queries) RecoverySources(ctx context.Context, orgID pgtype.UUID) ([]RecoverySourcesRow, error) {
	rows, err := q.db.Query(ctx, recoverySources, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecoverySourcesRow
	for rows.Next() {
		var i RecoverySourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DeletedAt,
			&i.KeyKept,
			&i.HasStorage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBackupKey = `-- name: UpsertBackupKey :exec
INSERT INTO backup_keys (node_id, org_id, sealed, fingerprint) VALUES ($1, $2, $3, $4)
ON CONFLICT (node_id) DO UPDATE SET sealed = excluded.sealed, fingerprint = excluded.fingerprint, stored_at = now()
`

type UpsertBackupKeyParams struct {
	NodeID      pgtype.UUID
	OrgID       pgtype.UUID
	Sealed      []byte
	Fingerprint string
}

func (q *Queries) UpsertBackupKey(ctx context.Context, arg UpsertBackupKeyParams) error {
	_, err := q.db.Exec(ctx, upsertBackupKey,
		arg.NodeID,
		arg.OrgID,
		arg.Sealed,
		arg.Fingerprint,
	)
	return err
}
