// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: eggs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrgEggs = `-- name: CountOrgEggs :one
SELECT count(*) FROM org_eggs WHERE org_id = $1
`

func (q *Queries) CountOrgEggs(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrgEggs, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrgEgg = `-- name: CreateOrgEgg :one
INSERT INTO org_eggs (org_id, name, egg, sha256, source_url, imported_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (org_id, sha256) DO NOTHING
RETURNING id, org_id, name, egg, sha256, source_url, imported_by, imported_at
`

type CreateOrgEggParams struct {
	OrgID      pgtype.UUID
	Name       string
	Egg        []byte
	Sha256     string
	SourceUrl  string
	ImportedBy pgtype.UUID
}

func (q *Queries) CreateOrgEgg(ctx context.Context, arg CreateOrgEggParams) (OrgEgg, error) {
	row := q.db.QueryRow(ctx, createOrgEgg,
		arg.OrgID,
		arg.Name,
		arg.Egg,
		arg.Sha256,
		arg.SourceUrl,
		arg.ImportedBy,
	)
	var i OrgEgg
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Egg,
		&i.Sha256,
		&i.SourceUrl,
		&i.ImportedBy,
		&i.ImportedAt,
	)
	return i, err
}

const deleteOrgEgg = `-- name: DeleteOrgEgg :execrows
DELETE FROM org_eggs WHERE org_id = $1 AND id = $2
`

type DeleteOrgEggParams struct {
	OrgID pgtype.UUID
	ID    pgtype.UUID
}

func (q *Queries) DeleteOrgEgg(ctx context.Context, arg DeleteOrgEggParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrgEgg, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrgEgg = `-- name: GetOrgEgg :one
SELECT id, org_id, name, egg, sha256, source_url, imported_by, imported_at FROM org_eggs WHERE org_id = $1 AND id = $2
`

type GetOrgEggParams struct {
	OrgID pgtype.UUID
	ID    pgtype.UUID
}

func (q *Queries) GetOrgEgg(ctx context.Context, arg GetOrgEggParams) (OrgEgg, error) {
	row := q.db.QueryRow(ctx, getOrgEgg, arg.OrgID, arg.ID)
	var i OrgEgg
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Egg,
		&i.Sha256,
		&i.SourceUrl,
		&i.ImportedBy,
		&i.ImportedAt,
	)
	return i, err
}

const listOrgEggs = `-- name: ListOrgEggs :many
SELECT o.id, o.org_id, o.name, o.egg, o.sha256, o.source_url, o.imported_by, o.imported_at, u.email AS imported_by_email
FROM org_eggs o LEFT JOIN users u ON u.id = o.imported_by
WHERE o.org_id = $1 ORDER BY o.name, o.id
`

type ListOrgEggsRow struct {
	ID              pgtype.UUID
	OrgID           pgtype.UUID
	Name            string
	Egg             []byte
	Sha256          string
	SourceUrl       string
	ImportedBy      pgtype.UUID
	ImportedAt      pgtype.Timestamptz
	ImportedByEmail pgtype.Text
}

func (q *Queries) ListOrgEggs(ctx context.Context, orgID pgtype.UUID) ([]ListOrgEggsRow, error) {
	rows, err := q.db.Query(ctx, listOrgEggs, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgEggsRow
	for rows.Next() {
		var i ListOrgEggsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Egg,
			&i.Sha256,
			&i.SourceUrl,
			&i.ImportedBy,
			&i.ImportedAt,
			&i.ImportedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgEggExists = `-- name: OrgEggExists :one
SELECT EXISTS (SELECT 1 FROM org_eggs WHERE org_id = $1 AND sha256 = $2)
`

type OrgEggExistsParams struct {
	OrgID  pgtype.UUID
	Sha256 string
}

func (q *Queries) OrgEggExists(ctx context.Context, arg OrgEggExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, orgEggExists, arg.OrgID, arg.Sha256)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
