// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grants.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteServerGrant = `-- name: DeleteServerGrant :execrows
DELETE FROM server_grants WHERE node_id = $1 AND server_id = $2 AND user_id = $3
`

type DeleteServerGrantParams struct {
	NodeID   pgtype.UUID
	ServerID string
	UserID   pgtype.UUID
}

func (q *Queries) DeleteServerGrant(ctx context.Context, arg DeleteServerGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServerGrant, arg.NodeID, arg.ServerID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const mirroredServerExists = `-- name: MirroredServerExists :one
SELECT EXISTS (SELECT 1 FROM m_servers WHERE node_id = $1 AND server_id = $2)
`

type MirroredServerExistsParams struct {
	NodeID   pgtype.UUID
	ServerID string
}

func (q *Queries) MirroredServerExists(ctx context.Context, arg MirroredServerExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, mirroredServerExists, arg.NodeID, arg.ServerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const nodeOrg = `-- name: NodeOrg :one
SELECT org_id FROM nodes WHERE id = $1 AND deleted_at IS NULL
`

// The org a live node belongs to.
func (q *Queries) NodeOrg(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, nodeOrg, id)
	var org_id pgtype.UUID
	err := row.Scan(&org_id)
	return org_id, err
}

const serverGrant = `-- name: ServerGrant :one
SELECT org_id, user_id, node_id, server_id, permissions, granted_by, updated_at FROM server_grants WHERE node_id = $1 AND server_id = $2 AND user_id = $3
`

type ServerGrantParams struct {
	NodeID   pgtype.UUID
	ServerID string
	UserID   pgtype.UUID
}

func (q *Queries) ServerGrant(ctx context.Context, arg ServerGrantParams) (ServerGrant, error) {
	row := q.db.QueryRow(ctx, serverGrant, arg.NodeID, arg.ServerID, arg.UserID)
	var i ServerGrant
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.NodeID,
		&i.ServerID,
		&i.Permissions,
		&i.GrantedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const serverGrants = `-- name: ServerGrants :many
SELECT g.org_id, g.user_id, g.node_id, g.server_id, g.permissions, g.granted_by, g.updated_at, u.email FROM server_grants g JOIN users u ON u.id = g.user_id
WHERE g.node_id = $1 AND g.server_id = $2
ORDER BY u.email
`

type ServerGrantsParams struct {
	NodeID   pgtype.UUID
	ServerID string
}

type ServerGrantsRow struct {
	OrgID       pgtype.UUID
	UserID      pgtype.UUID
	NodeID      pgtype.UUID
	ServerID    string
	Permissions []string
	GrantedBy   pgtype.UUID
	UpdatedAt   pgtype.Timestamptz
	Email       string
}

func (q *Queries) ServerGrants(ctx context.Context, arg ServerGrantsParams) ([]ServerGrantsRow, error) {
	rows, err := q.db.Query(ctx, serverGrants, arg.NodeID, arg.ServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServerGrantsRow
	for rows.Next() {
		var i ServerGrantsRow
		if err := rows.Scan(
			&i.OrgID,
			&i.UserID,
			&i.NodeID,
			&i.ServerID,
			&i.Permissions,
			&i.GrantedBy,
			&i.UpdatedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setServerGrant = `-- name: SetServerGrant :exec
INSERT INTO server_grants (org_id, user_id, node_id, server_id, permissions, granted_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (node_id, server_id, user_id)
DO UPDATE SET permissions = excluded.permissions, granted_by = excluded.granted_by, updated_at = now()
`

type SetServerGrantParams struct {
	OrgID       pgtype.UUID
	UserID      pgtype.UUID
	NodeID      pgtype.UUID
	ServerID    string
	Permissions []string
	GrantedBy   pgtype.UUID
}

func (q *Queries) SetServerGrant(ctx context.Context, arg SetServerGrantParams) error {
	_, err := q.db.Exec(ctx, setServerGrant,
		arg.OrgID,
		arg.UserID,
		arg.NodeID,
		arg.ServerID,
		arg.Permissions,
		arg.GrantedBy,
	)
	return err
}
