// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instances.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const answerNodeRequest = `-- name: AnswerNodeRequest :one
UPDATE node_requests SET response = $2, error_code = $3, error = $4, done_at = now()
WHERE id = $1 RETURNING origin
`

type AnswerNodeRequestParams struct {
	ID        int64
	Response  []byte
	ErrorCode string
	Error     string
}

func (q *Queries) AnswerNodeRequest(ctx context.Context, arg AnswerNodeRequestParams) (string, error) {
	row := q.db.QueryRow(ctx, answerNodeRequest,
		arg.ID,
		arg.Response,
		arg.ErrorCode,
		arg.Error,
	)
	var origin string
	err := row.Scan(&origin)
	return origin, err
}

const clearInstanceConnections = `-- name: ClearInstanceConnections :exec
DELETE FROM node_connections WHERE instance_id = $1
`

func (q *Queries) ClearInstanceConnections(ctx context.Context, instanceID string) error {
	_, err := q.db.Exec(ctx, clearInstanceConnections, instanceID)
	return err
}

const clearNodeConnection = `-- name: ClearNodeConnection :exec
DELETE FROM node_connections WHERE node_id = $1 AND instance_id = $2
`

type ClearNodeConnectionParams struct {
	NodeID     pgtype.UUID
	InstanceID string
}

func (q *Queries) ClearNodeConnection(ctx context.Context, arg ClearNodeConnectionParams) error {
	_, err := q.db.Exec(ctx, clearNodeConnection, arg.NodeID, arg.InstanceID)
	return err
}

const createNodeRequest = `-- name: CreateNodeRequest :one
INSERT INTO node_requests (node_id, origin, target, method, request)
VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type CreateNodeRequestParams struct {
	NodeID  pgtype.UUID
	Origin  string
	Target  string
	Method  string
	Request []byte
}

func (q *Queries) CreateNodeRequest(ctx context.Context, arg CreateNodeRequestParams) (int64, error) {
	row := q.db.QueryRow(ctx, createNodeRequest,
		arg.NodeID,
		arg.Origin,
		arg.Target,
		arg.Method,
		arg.Request,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getNodeRequest = `-- name: GetNodeRequest :one
SELECT id, node_id, origin, target, method, request, response, error_code, error, created_at, claimed_at, done_at FROM node_requests WHERE id = $1
`

func (q *Queries) GetNodeRequest(ctx context.Context, id int64) (NodeRequest, error) {
	row := q.db.QueryRow(ctx, getNodeRequest, id)
	var i NodeRequest
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Origin,
		&i.Target,
		&i.Method,
		&i.Request,
		&i.Response,
		&i.ErrorCode,
		&i.Error,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.DoneAt,
	)
	return i, err
}

const instanceAlive = `-- name: InstanceAlive :exec
INSERT INTO panel_instances (id) VALUES ($1)
ON CONFLICT (id) DO UPDATE SET seen_at = now()
`

func (q *Queries) InstanceAlive(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, instanceAlive, id)
	return err
}

const instanceGone = `-- name: InstanceGone :exec
DELETE FROM panel_instances WHERE id = $1
`

func (q *Queries) InstanceGone(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, instanceGone, id)
	return err
}

const nodeHolder = `-- name: NodeHolder :one
SELECT c.instance_id FROM node_connections c
JOIN panel_instances i ON i.id = c.instance_id
WHERE c.node_id = $1 AND i.seen_at > now() - make_interval(secs => $2::float8)
`

type NodeHolderParams struct {
	NodeID    pgtype.UUID
	StaleSecs float64
}

// The instance holding a node, if it's alive.
func (q *Queries) NodeHolder(ctx context.Context, arg NodeHolderParams) (string, error) {
	row := q.db.QueryRow(ctx, nodeHolder, arg.NodeID, arg.StaleSecs)
	var instance_id string
	err := row.Scan(&instance_id)
	return instance_id, err
}

const pendingNodeRequests = `-- name: PendingNodeRequests :many
SELECT id FROM node_requests
WHERE target = $1 AND claimed_at IS NULL AND created_at < now() - interval '1 second'
`

// Requests for this instance that haven't been answered (a fallback for a
// missed notification).
func (q *Queries) PendingNodeRequests(ctx context.Context, target string) ([]int64, error) {
	rows, err := q.db.Query(ctx, pendingNodeRequests, target)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneInstances = `-- name: PruneInstances :exec
DELETE FROM panel_instances WHERE seen_at < now() - make_interval(secs => $1::float8)
`

func (q *Queries) PruneInstances(ctx context.Context, staleSecs float64) error {
	_, err := q.db.Exec(ctx, pruneInstances, staleSecs)
	return err
}

const pruneNodeRequests = `-- name: PruneNodeRequests :exec
DELETE FROM node_requests WHERE created_at < now() - interval '1 hour'
`

func (q *Queries) PruneNodeRequests(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneNodeRequests)
	return err
}

const setNodeConnection = `-- name: SetNodeConnection :exec
INSERT INTO node_connections (node_id, instance_id) VALUES ($1, $2)
ON CONFLICT (node_id) DO UPDATE SET instance_id = EXCLUDED.instance_id, connected_at = now()
`

type SetNodeConnectionParams struct {
	NodeID     pgtype.UUID
	InstanceID string
}

func (q *Queries) SetNodeConnection(ctx context.Context, arg SetNodeConnectionParams) error {
	_, err := q.db.Exec(ctx, setNodeConnection, arg.NodeID, arg.InstanceID)
	return err
}

const takeNodeRequest = `-- name: TakeNodeRequest :one
UPDATE node_requests SET claimed_at = now()
WHERE id = $1 AND target = $2 AND claimed_at IS NULL
RETURNING id, node_id, origin, target, method, request, response, error_code, error, created_at, claimed_at, done_at
`

type TakeNodeRequestParams struct {
	ID     int64
	Target string
}

// Claims a request, so a notification and the fallback poll can't both run it.
func (q *Queries) TakeNodeRequest(ctx context.Context, arg TakeNodeRequestParams) (NodeRequest, error) {
	row := q.db.QueryRow(ctx, takeNodeRequest, arg.ID, arg.Target)
	var i NodeRequest
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Origin,
		&i.Target,
		&i.Method,
		&i.Request,
		&i.Response,
		&i.ErrorCode,
		&i.Error,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.DoneAt,
	)
	return i, err
}
