// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mirror.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMirrorServer = `-- name: DeleteMirrorServer :exec
DELETE FROM m_servers WHERE node_id = $1 AND server_id = $2
`

type DeleteMirrorServerParams struct {
	NodeID   pgtype.UUID
	ServerID string
}

func (q *Queries) DeleteMirrorServer(ctx context.Context, arg DeleteMirrorServerParams) error {
	_, err := q.db.Exec(ctx, deleteMirrorServer, arg.NodeID, arg.ServerID)
	return err
}

const deleteMirrorServers = `-- name: DeleteMirrorServers :exec
DELETE FROM m_servers WHERE node_id = $1
`

func (q *Queries) DeleteMirrorServers(ctx context.Context, nodeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMirrorServers, nodeID)
	return err
}

const getNodeAcked = `-- name: GetNodeAcked :one
SELECT last_acked_seq FROM nodes WHERE id = $1
`

func (q *Queries) GetNodeAcked(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getNodeAcked, id)
	var last_acked_seq int64
	err := row.Scan(&last_acked_seq)
	return last_acked_seq, err
}

const listMirrorServers = `-- name: ListMirrorServers :many
SELECT node_id, server_id, name, version, state, desired_state, install_state, install_error, egg_name, egg_source, config, created_at, updated_at, synced_at FROM m_servers WHERE node_id = $1 ORDER BY name, server_id
`

func (q *Queries) ListMirrorServers(ctx context.Context, nodeID pgtype.UUID) ([]MServer, error) {
	rows, err := q.db.Query(ctx, listMirrorServers, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MServer
	for rows.Next() {
		var i MServer
		if err := rows.Scan(
			&i.NodeID,
			&i.ServerID,
			&i.Name,
			&i.Version,
			&i.State,
			&i.DesiredState,
			&i.InstallState,
			&i.InstallError,
			&i.EggName,
			&i.EggSource,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMirrorServerState = `-- name: SetMirrorServerState :exec
UPDATE m_servers SET state = $3, synced_at = now() WHERE node_id = $1 AND server_id = $2
`

type SetMirrorServerStateParams struct {
	NodeID   pgtype.UUID
	ServerID string
	State    string
}

func (q *Queries) SetMirrorServerState(ctx context.Context, arg SetMirrorServerStateParams) error {
	_, err := q.db.Exec(ctx, setMirrorServerState, arg.NodeID, arg.ServerID, arg.State)
	return err
}

const setNodeAcked = `-- name: SetNodeAcked :exec
UPDATE nodes SET last_acked_seq = $2 WHERE id = $1
`

type SetNodeAckedParams struct {
	ID           pgtype.UUID
	LastAckedSeq int64
}

func (q *Queries) SetNodeAcked(ctx context.Context, arg SetNodeAckedParams) error {
	_, err := q.db.Exec(ctx, setNodeAcked, arg.ID, arg.LastAckedSeq)
	return err
}

const upsertMirrorServer = `-- name: UpsertMirrorServer :exec
INSERT INTO m_servers (node_id, server_id, name, version, state, desired_state, install_state,
                       install_error, egg_name, egg_source, config, created_at, updated_at, synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, now())
ON CONFLICT (node_id, server_id) DO UPDATE SET
    name = EXCLUDED.name, version = EXCLUDED.version, state = EXCLUDED.state,
    desired_state = EXCLUDED.desired_state, install_state = EXCLUDED.install_state,
    install_error = EXCLUDED.install_error, egg_name = EXCLUDED.egg_name,
    egg_source = EXCLUDED.egg_source, config = EXCLUDED.config,
    created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, synced_at = now()
WHERE m_servers.version <= EXCLUDED.version
`

type UpsertMirrorServerParams struct {
	NodeID       pgtype.UUID
	ServerID     string
	Name         string
	Version      int64
	State        string
	DesiredState string
	InstallState string
	InstallError string
	EggName      string
	EggSource    string
	Config       []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// A fetch is the node's current answer; an older one (a slower fetch that
// lost a race) doesn't replace a newer version.
func (q *Queries) UpsertMirrorServer(ctx context.Context, arg UpsertMirrorServerParams) error {
	_, err := q.db.Exec(ctx, upsertMirrorServer,
		arg.NodeID,
		arg.ServerID,
		arg.Name,
		arg.Version,
		arg.State,
		arg.DesiredState,
		arg.InstallState,
		arg.InstallError,
		arg.EggName,
		arg.EggSource,
		arg.Config,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
