// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type EmailCode struct {
	ID            pgtype.UUID
	Email         string
	CodeHash      []byte
	LinkTokenHash []byte
	Purpose       string
	Attempts      int32
	ExpiresAt     pgtype.Timestamptz
	UsedAt        pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type JoinToken struct {
	ID        pgtype.UUID
	OrgID     pgtype.UUID
	TokenHash []byte
	Name      string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	NodeID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type MBackup struct {
	NodeID        pgtype.UUID
	ServerID      string
	BackupID      string
	Kind          string
	Status        string
	Locked        bool
	Size          int64
	Files         int64
	DestinationID string
	Error         string
	Warning       string
	CreatedBy     string
	CreatedAt     pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
}

type MSchedule struct {
	NodeID     pgtype.UUID
	ServerID   string
	ScheduleID string
	Name       string
	Enabled    bool
	Version    int64
	NextRun    pgtype.Timestamptz
	LastRun    pgtype.Timestamptz
	Definition []byte
}

type MServer struct {
	NodeID       pgtype.UUID
	ServerID     string
	Name         string
	Version      int64
	State        string
	DesiredState string
	InstallState string
	InstallError string
	EggName      string
	EggSource    string
	Config       []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	SyncedAt     pgtype.Timestamptz
}

type Node struct {
	ID              pgtype.UUID
	OrgID           pgtype.UUID
	Name            string
	ShortID         string
	PublicKey       []byte
	Facts           []byte
	WingsVersion    string
	ProtocolVersion int32
	LastSeenAt      pgtype.Timestamptz
	LastAckedSeq    int64
	KeyRevokedAt    pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	PublicIpv4      *netip.Addr
	PublicIpv6      *netip.Addr
	DnsIpv4         *netip.Addr
	DnsIpv6         *netip.Addr
}

type NodeConnection struct {
	NodeID      pgtype.UUID
	InstanceID  string
	ConnectedAt pgtype.Timestamptz
}

type NodeRequest struct {
	ID        int64
	NodeID    pgtype.UUID
	Origin    string
	Target    string
	Method    string
	Request   []byte
	Response  []byte
	ErrorCode string
	Error     string
	CreatedAt pgtype.Timestamptz
	ClaimedAt pgtype.Timestamptz
	DoneAt    pgtype.Timestamptz
}

type Org struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type PanelInstance struct {
	ID        string
	StartedAt pgtype.Timestamptz
	SeenAt    pgtype.Timestamptz
}

type Passkey struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	CredentialID []byte
	Credential   []byte
	Name         string
	CreatedAt    pgtype.Timestamptz
	LastUsedAt   pgtype.Timestamptz
}

type PendingSignin struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash []byte
	Attempts  int32
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type RateEvent struct {
	Key string
	At  pgtype.Timestamptz
}

type RecoveryCode struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	CodeHash  []byte
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type RolloutNode struct {
	RolloutID   pgtype.UUID
	NodeID      pgtype.UUID
	Stage       int32
	Status      string
	FromVersion string
	Error       string
	SentAt      pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
}

type Session struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	TokenHash  []byte
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	ReauthAt   pgtype.Timestamptz
	Ip         *netip.Addr
	UserAgent  string
	RevokedAt  pgtype.Timestamptz
}

type TotpSetup struct {
	UserID    pgtype.UUID
	Secret    []byte
	ExpiresAt pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	Email           string
	EmailVerifiedAt pgtype.Timestamptz
	Name            string
	CreatedAt       pgtype.Timestamptz
	WebauthnHandle  []byte
	TotpSecret      []byte
	TotpEnabledAt   pgtype.Timestamptz
	TotpLastStep    int64
}

type WebauthnCeremony struct {
	ID        pgtype.UUID
	Purpose   string
	SessionID pgtype.UUID
	Data      []byte
	ExpiresAt pgtype.Timestamptz
}

type WingsRollout struct {
	ID             pgtype.UUID
	Version        string
	State          string
	Stage          int32
	StageStartedAt pgtype.Timestamptz
	Reason         string
	CreatedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
}
