// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type JoinToken struct {
	ID        pgtype.UUID
	OrgID     pgtype.UUID
	TokenHash []byte
	Name      string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	NodeID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type MBackup struct {
	NodeID        pgtype.UUID
	ServerID      string
	BackupID      string
	Kind          string
	Status        string
	Locked        bool
	Size          int64
	Files         int64
	DestinationID string
	Error         string
	Warning       string
	CreatedBy     string
	CreatedAt     pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
}

type MSchedule struct {
	NodeID     pgtype.UUID
	ServerID   string
	ScheduleID string
	Name       string
	Enabled    bool
	Version    int64
	NextRun    pgtype.Timestamptz
	LastRun    pgtype.Timestamptz
	Definition []byte
}

type MServer struct {
	NodeID       pgtype.UUID
	ServerID     string
	Name         string
	Version      int64
	State        string
	DesiredState string
	InstallState string
	InstallError string
	EggName      string
	EggSource    string
	Config       []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	SyncedAt     pgtype.Timestamptz
}

type Node struct {
	ID              pgtype.UUID
	OrgID           pgtype.UUID
	Name            string
	ShortID         string
	PublicKey       []byte
	Facts           []byte
	WingsVersion    string
	ProtocolVersion int32
	LastSeenAt      pgtype.Timestamptz
	LastAckedSeq    int64
	KeyRevokedAt    pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	PublicIpv4      *netip.Addr
	PublicIpv6      *netip.Addr
	DnsIpv4         *netip.Addr
	DnsIpv6         *netip.Addr
}

type NodeConnection struct {
	NodeID      pgtype.UUID
	InstanceID  string
	ConnectedAt pgtype.Timestamptz
}

type NodeRequest struct {
	ID        int64
	NodeID    pgtype.UUID
	Origin    string
	Target    string
	Method    string
	Request   []byte
	Response  []byte
	ErrorCode string
	Error     string
	CreatedAt pgtype.Timestamptz
	ClaimedAt pgtype.Timestamptz
	DoneAt    pgtype.Timestamptz
}

type Org struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type PanelInstance struct {
	ID        string
	StartedAt pgtype.Timestamptz
	SeenAt    pgtype.Timestamptz
}
