// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package store

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJoinToken = `-- name: CreateJoinToken :one
INSERT INTO join_tokens (org_id, token_hash, name, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, token_hash, name, expires_at, used_at, node_id, created_at
`

type CreateJoinTokenParams struct {
	OrgID     pgtype.UUID
	TokenHash []byte
	Name      string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateJoinToken(ctx context.Context, arg CreateJoinTokenParams) (JoinToken, error) {
	row := q.db.QueryRow(ctx, createJoinToken,
		arg.OrgID,
		arg.TokenHash,
		arg.Name,
		arg.ExpiresAt,
	)
	var i JoinToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TokenHash,
		&i.Name,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.NodeID,
		&i.CreatedAt,
	)
	return i, err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (org_id, name, short_id, public_key, facts, wings_version)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, name, short_id, public_key, facts, wings_version, protocol_version, last_seen_at, last_acked_seq, key_revoked_at, deleted_at, created_at, public_ipv4, public_ipv6, dns_ipv4, dns_ipv6
`

type CreateNodeParams struct {
	OrgID        pgtype.UUID
	Name         string
	ShortID      string
	PublicKey    []byte
	Facts        []byte
	WingsVersion string
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.OrgID,
		arg.Name,
		arg.ShortID,
		arg.PublicKey,
		arg.Facts,
		arg.WingsVersion,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ShortID,
		&i.PublicKey,
		&i.Facts,
		&i.WingsVersion,
		&i.ProtocolVersion,
		&i.LastSeenAt,
		&i.LastAckedSeq,
		&i.KeyRevokedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.PublicIpv4,
		&i.PublicIpv6,
		&i.DnsIpv4,
		&i.DnsIpv6,
	)
	return i, err
}

const createOrg = `-- name: CreateOrg :one
INSERT INTO orgs (name) VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreateOrg(ctx context.Context, name string) (Org, error) {
	row := q.db.QueryRow(ctx, createOrg, name)
	var i Org
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getJoinTokenForUpdate = `-- name: GetJoinTokenForUpdate :one
SELECT id, org_id, token_hash, name, expires_at, used_at, node_id, created_at FROM join_tokens WHERE token_hash = $1 FOR UPDATE
`

func (q *Queries) GetJoinTokenForUpdate(ctx context.Context, tokenHash []byte) (JoinToken, error) {
	row := q.db.QueryRow(ctx, getJoinTokenForUpdate, tokenHash)
	var i JoinToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TokenHash,
		&i.Name,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.NodeID,
		&i.CreatedAt,
	)
	return i, err
}

const getNode = `-- name: GetNode :one
SELECT id, org_id, name, short_id, public_key, facts, wings_version, protocol_version, last_seen_at, last_acked_seq, key_revoked_at, deleted_at, created_at, public_ipv4, public_ipv6, dns_ipv4, dns_ipv6 FROM nodes WHERE id = $1
`

func (q *Queries) GetNode(ctx context.Context, id pgtype.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ShortID,
		&i.PublicKey,
		&i.Facts,
		&i.WingsVersion,
		&i.ProtocolVersion,
		&i.LastSeenAt,
		&i.LastAckedSeq,
		&i.KeyRevokedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.PublicIpv4,
		&i.PublicIpv6,
		&i.DnsIpv4,
		&i.DnsIpv6,
	)
	return i, err
}

const nodeConnected = `-- name: NodeConnected :exec
UPDATE nodes SET last_seen_at = now(), wings_version = $2, protocol_version = $3 WHERE id = $1
`

type NodeConnectedParams struct {
	ID              pgtype.UUID
	WingsVersion    string
	ProtocolVersion int32
}

func (q *Queries) NodeConnected(ctx context.Context, arg NodeConnectedParams) error {
	_, err := q.db.Exec(ctx, nodeConnected, arg.ID, arg.WingsVersion, arg.ProtocolVersion)
	return err
}

const nodeDNS = `-- name: NodeDNS :one
SELECT short_id, public_ipv4, public_ipv6, dns_ipv4, dns_ipv6 FROM nodes WHERE id = $1
`

type NodeDNSRow struct {
	ShortID    string
	PublicIpv4 *netip.Addr
	PublicIpv6 *netip.Addr
	DnsIpv4    *netip.Addr
	DnsIpv6    *netip.Addr
}

func (q *Queries) NodeDNS(ctx context.Context, id pgtype.UUID) (NodeDNSRow, error) {
	row := q.db.QueryRow(ctx, nodeDNS, id)
	var i NodeDNSRow
	err := row.Scan(
		&i.ShortID,
		&i.PublicIpv4,
		&i.PublicIpv6,
		&i.DnsIpv4,
		&i.DnsIpv6,
	)
	return i, err
}

const nodeSeen = `-- name: NodeSeen :exec
UPDATE nodes SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) NodeSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, nodeSeen, id)
	return err
}

const relinkNode = `-- name: RelinkNode :one
UPDATE nodes
SET public_key = $2, wings_version = $3, facts = $4, key_revoked_at = NULL, deleted_at = NULL
WHERE id = $1
RETURNING id, org_id, name, short_id, public_key, facts, wings_version, protocol_version, last_seen_at, last_acked_seq, key_revoked_at, deleted_at, created_at, public_ipv4, public_ipv6, dns_ipv4, dns_ipv6
`

type RelinkNodeParams struct {
	ID           pgtype.UUID
	PublicKey    []byte
	WingsVersion string
	Facts        []byte
}

func (q *Queries) RelinkNode(ctx context.Context, arg RelinkNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, relinkNode,
		arg.ID,
		arg.PublicKey,
		arg.WingsVersion,
		arg.Facts,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ShortID,
		&i.PublicKey,
		&i.Facts,
		&i.WingsVersion,
		&i.ProtocolVersion,
		&i.LastSeenAt,
		&i.LastAckedSeq,
		&i.KeyRevokedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.PublicIpv4,
		&i.PublicIpv6,
		&i.DnsIpv4,
		&i.DnsIpv6,
	)
	return i, err
}

const setNodeDNS = `-- name: SetNodeDNS :exec
UPDATE nodes SET dns_ipv4 = $2, dns_ipv6 = $3 WHERE id = $1
`

type SetNodeDNSParams struct {
	ID      pgtype.UUID
	DnsIpv4 *netip.Addr
	DnsIpv6 *netip.Addr
}

func (q *Queries) SetNodeDNS(ctx context.Context, arg SetNodeDNSParams) error {
	_, err := q.db.Exec(ctx, setNodeDNS, arg.ID, arg.DnsIpv4, arg.DnsIpv6)
	return err
}

const setNodeIPv4 = `-- name: SetNodeIPv4 :exec
UPDATE nodes SET public_ipv4 = $2 WHERE id = $1
`

type SetNodeIPv4Params struct {
	ID         pgtype.UUID
	PublicIpv4 *netip.Addr
}

func (q *Queries) SetNodeIPv4(ctx context.Context, arg SetNodeIPv4Params) error {
	_, err := q.db.Exec(ctx, setNodeIPv4, arg.ID, arg.PublicIpv4)
	return err
}

const setNodeIPv6 = `-- name: SetNodeIPv6 :exec
UPDATE nodes SET public_ipv6 = $2 WHERE id = $1
`

type SetNodeIPv6Params struct {
	ID         pgtype.UUID
	PublicIpv6 *netip.Addr
}

func (q *Queries) SetNodeIPv6(ctx context.Context, arg SetNodeIPv6Params) error {
	_, err := q.db.Exec(ctx, setNodeIPv6, arg.ID, arg.PublicIpv6)
	return err
}

const shortIDTaken = `-- name: ShortIDTaken :one
SELECT EXISTS (SELECT 1 FROM nodes WHERE short_id = $1)
`

func (q *Queries) ShortIDTaken(ctx context.Context, shortID string) (bool, error) {
	row := q.db.QueryRow(ctx, shortIDTaken, shortID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const useJoinToken = `-- name: UseJoinToken :exec
UPDATE join_tokens SET used_at = now(), node_id = $2 WHERE id = $1
`

type UseJoinTokenParams struct {
	ID     pgtype.UUID
	NodeID pgtype.UUID
}

func (q *Queries) UseJoinToken(ctx context.Context, arg UseJoinTokenParams) error {
	_, err := q.db.Exec(ctx, useJoinToken, arg.ID, arg.NodeID)
	return err
}
