// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package store

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJoinToken = `-- name: CreateJoinToken :one
INSERT INTO join_tokens (org_id, token_hash, name, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, token_hash, name, expires_at, used_at, node_id, created_at, owner_pin
`

type CreateJoinTokenParams struct {
	OrgID     pgtype.UUID
	TokenHash []byte
	Name      string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateJoinToken(ctx context.Context, arg CreateJoinTokenParams) (JoinToken, error) {
	row := q.db.QueryRow(ctx, createJoinToken,
		arg.OrgID,
		arg.TokenHash,
		arg.Name,
		arg.ExpiresAt,
	)
	var i JoinToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TokenHash,
		&i.Name,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.NodeID,
		&i.CreatedAt,
		&i.OwnerPin,
	)
	return i, err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (org_id, name, short_id, public_key, facts, wings_version)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, name, short_id, public_key, facts, wings_version, protocol_version, last_seen_at, last_acked_seq, key_revoked_at, deleted_at, created_at, public_ipv4, public_ipv6, dns_ipv4, dns_ipv6, sftp_enabled, sftp_port, sftp_host_key, sftp_allowed
`

type CreateNodeParams struct {
	OrgID        pgtype.UUID
	Name         string
	ShortID      string
	PublicKey    []byte
	Facts        []byte
	WingsVersion string
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.OrgID,
		arg.Name,
		arg.ShortID,
		arg.PublicKey,
		arg.Facts,
		arg.WingsVersion,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ShortID,
		&i.PublicKey,
		&i.Facts,
		&i.WingsVersion,
		&i.ProtocolVersion,
		&i.LastSeenAt,
		&i.LastAckedSeq,
		&i.KeyRevokedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.PublicIpv4,
		&i.PublicIpv6,
		&i.DnsIpv4,
		&i.DnsIpv6,
		&i.SftpEnabled,
		&i.SftpPort,
		&i.SftpHostKey,
		&i.SftpAllowed,
	)
	return i, err
}

const createOrg = `-- name: CreateOrg :one
INSERT INTO orgs (name) VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreateOrg(ctx context.Context, name string) (Org, error) {
	row := q.db.QueryRow(ctx, createOrg, name)
	var i Org
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const forgetNodeBackups = `-- name: ForgetNodeBackups :exec
DELETE FROM m_backups WHERE node_id = $1
`

func (q *Queries) ForgetNodeBackups(ctx context.Context, nodeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, forgetNodeBackups, nodeID)
	return err
}

const forgetNodeGrants = `-- name: ForgetNodeGrants :exec
DELETE FROM server_grants WHERE node_id = $1
`

func (q *Queries) ForgetNodeGrants(ctx context.Context, nodeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, forgetNodeGrants, nodeID)
	return err
}

const forgetNodeJobs = `-- name: ForgetNodeJobs :exec

DELETE FROM m_jobs WHERE node_id = $1
`

// A removed node's mirror and members' grants: they were about servers the
// Panel no longer manages.
func (q *Queries) ForgetNodeJobs(ctx context.Context, nodeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, forgetNodeJobs, nodeID)
	return err
}

const forgetNodeSchedules = `-- name: ForgetNodeSchedules :exec
DELETE FROM m_schedules WHERE node_id = $1
`

func (q *Queries) ForgetNodeSchedules(ctx context.Context, nodeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, forgetNodeSchedules, nodeID)
	return err
}

const forgetNodeServers = `-- name: ForgetNodeServers :exec
DELETE FROM m_servers WHERE node_id = $1
`

func (q *Queries) ForgetNodeServers(ctx context.Context, nodeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, forgetNodeServers, nodeID)
	return err
}

const getJoinTokenForUpdate = `-- name: GetJoinTokenForUpdate :one
SELECT id, org_id, token_hash, name, expires_at, used_at, node_id, created_at, owner_pin FROM join_tokens WHERE token_hash = $1 FOR UPDATE
`

func (q *Queries) GetJoinTokenForUpdate(ctx context.Context, tokenHash []byte) (JoinToken, error) {
	row := q.db.QueryRow(ctx, getJoinTokenForUpdate, tokenHash)
	var i JoinToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TokenHash,
		&i.Name,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.NodeID,
		&i.CreatedAt,
		&i.OwnerPin,
	)
	return i, err
}

const getNode = `-- name: GetNode :one
SELECT id, org_id, name, short_id, public_key, facts, wings_version, protocol_version, last_seen_at, last_acked_seq, key_revoked_at, deleted_at, created_at, public_ipv4, public_ipv6, dns_ipv4, dns_ipv6, sftp_enabled, sftp_port, sftp_host_key, sftp_allowed FROM nodes WHERE id = $1
`

func (q *Queries) GetNode(ctx context.Context, id pgtype.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ShortID,
		&i.PublicKey,
		&i.Facts,
		&i.WingsVersion,
		&i.ProtocolVersion,
		&i.LastSeenAt,
		&i.LastAckedSeq,
		&i.KeyRevokedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.PublicIpv4,
		&i.PublicIpv6,
		&i.DnsIpv4,
		&i.DnsIpv6,
		&i.SftpEnabled,
		&i.SftpPort,
		&i.SftpHostKey,
		&i.SftpAllowed,
	)
	return i, err
}

const nodeConnected = `-- name: NodeConnected :exec
UPDATE nodes SET last_seen_at = now(), wings_version = $2, protocol_version = $3,
    last_acked_seq = CASE WHEN wings_version <> '' AND wings_version <> $2 THEN -1 ELSE last_acked_seq END
WHERE id = $1
`

type NodeConnectedParams struct {
	ID              pgtype.UUID
	WingsVersion    string
	ProtocolVersion int32
}

// A node on a new Wings version gets a fresh mirror snapshot (last_acked_seq
// -1), so what a new version reports about servers shows up at once.
func (q *Queries) NodeConnected(ctx context.Context, arg NodeConnectedParams) error {
	_, err := q.db.Exec(ctx, nodeConnected, arg.ID, arg.WingsVersion, arg.ProtocolVersion)
	return err
}

const nodeDNS = `-- name: NodeDNS :one
SELECT short_id, public_ipv4, public_ipv6, dns_ipv4, dns_ipv6 FROM nodes WHERE id = $1
`

type NodeDNSRow struct {
	ShortID    string
	PublicIpv4 *netip.Addr
	PublicIpv6 *netip.Addr
	DnsIpv4    *netip.Addr
	DnsIpv6    *netip.Addr
}

func (q *Queries) NodeDNS(ctx context.Context, id pgtype.UUID) (NodeDNSRow, error) {
	row := q.db.QueryRow(ctx, nodeDNS, id)
	var i NodeDNSRow
	err := row.Scan(
		&i.ShortID,
		&i.PublicIpv4,
		&i.PublicIpv6,
		&i.DnsIpv4,
		&i.DnsIpv6,
	)
	return i, err
}

const nodeSeen = `-- name: NodeSeen :exec
UPDATE nodes SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) NodeSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, nodeSeen, id)
	return err
}

const relinkNode = `-- name: RelinkNode :one
UPDATE nodes
SET public_key = $2, wings_version = $3, facts = $4, key_revoked_at = NULL, deleted_at = NULL
WHERE id = $1
RETURNING id, org_id, name, short_id, public_key, facts, wings_version, protocol_version, last_seen_at, last_acked_seq, key_revoked_at, deleted_at, created_at, public_ipv4, public_ipv6, dns_ipv4, dns_ipv6, sftp_enabled, sftp_port, sftp_host_key, sftp_allowed
`

type RelinkNodeParams struct {
	ID           pgtype.UUID
	PublicKey    []byte
	WingsVersion string
	Facts        []byte
}

func (q *Queries) RelinkNode(ctx context.Context, arg RelinkNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, relinkNode,
		arg.ID,
		arg.PublicKey,
		arg.WingsVersion,
		arg.Facts,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ShortID,
		&i.PublicKey,
		&i.Facts,
		&i.WingsVersion,
		&i.ProtocolVersion,
		&i.LastSeenAt,
		&i.LastAckedSeq,
		&i.KeyRevokedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.PublicIpv4,
		&i.PublicIpv6,
		&i.DnsIpv4,
		&i.DnsIpv6,
		&i.SftpEnabled,
		&i.SftpPort,
		&i.SftpHostKey,
		&i.SftpAllowed,
	)
	return i, err
}

const removeNode = `-- name: RemoveNode :execrows
UPDATE nodes SET deleted_at = now(), key_revoked_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

// Removing a node: its key is refused from now on (relinking with a join
// token brings it back), and it's hidden everywhere.
func (q *Queries) RemoveNode(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, removeNode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renameNode = `-- name: RenameNode :execrows
UPDATE nodes SET name = $2 WHERE id = $1 AND deleted_at IS NULL
`

type RenameNodeParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) RenameNode(ctx context.Context, arg RenameNodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameNode, arg.ID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setJoinTokenPin = `-- name: SetJoinTokenPin :execrows
UPDATE join_tokens SET owner_pin = $3
WHERE token_hash = $1 AND org_id = $2 AND used_at IS NULL AND expires_at > now() AND owner_pin IS NULL
`

type SetJoinTokenPinParams struct {
	TokenHash []byte
	OrgID     pgtype.UUID
	OwnerPin  []byte
}

// Only on an org's own unused, unexpired token, and only once.
func (q *Queries) SetJoinTokenPin(ctx context.Context, arg SetJoinTokenPinParams) (int64, error) {
	result, err := q.db.Exec(ctx, setJoinTokenPin, arg.TokenHash, arg.OrgID, arg.OwnerPin)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setNodeDNS = `-- name: SetNodeDNS :exec
UPDATE nodes SET dns_ipv4 = $2, dns_ipv6 = $3 WHERE id = $1
`

type SetNodeDNSParams struct {
	ID      pgtype.UUID
	DnsIpv4 *netip.Addr
	DnsIpv6 *netip.Addr
}

func (q *Queries) SetNodeDNS(ctx context.Context, arg SetNodeDNSParams) error {
	_, err := q.db.Exec(ctx, setNodeDNS, arg.ID, arg.DnsIpv4, arg.DnsIpv6)
	return err
}

const setNodeIPv4 = `-- name: SetNodeIPv4 :exec
UPDATE nodes SET public_ipv4 = $2 WHERE id = $1
`

type SetNodeIPv4Params struct {
	ID         pgtype.UUID
	PublicIpv4 *netip.Addr
}

func (q *Queries) SetNodeIPv4(ctx context.Context, arg SetNodeIPv4Params) error {
	_, err := q.db.Exec(ctx, setNodeIPv4, arg.ID, arg.PublicIpv4)
	return err
}

const setNodeIPv6 = `-- name: SetNodeIPv6 :exec
UPDATE nodes SET public_ipv6 = $2 WHERE id = $1
`

type SetNodeIPv6Params struct {
	ID         pgtype.UUID
	PublicIpv6 *netip.Addr
}

func (q *Queries) SetNodeIPv6(ctx context.Context, arg SetNodeIPv6Params) error {
	_, err := q.db.Exec(ctx, setNodeIPv6, arg.ID, arg.PublicIpv6)
	return err
}

const setNodeSFTP = `-- name: SetNodeSFTP :exec
UPDATE nodes SET sftp_enabled = $2, sftp_port = $3, sftp_host_key = $4 WHERE id = $1
`

type SetNodeSFTPParams struct {
	ID          pgtype.UUID
	SftpEnabled bool
	SftpPort    int32
	SftpHostKey string
}

func (q *Queries) SetNodeSFTP(ctx context.Context, arg SetNodeSFTPParams) error {
	_, err := q.db.Exec(ctx, setNodeSFTP,
		arg.ID,
		arg.SftpEnabled,
		arg.SftpPort,
		arg.SftpHostKey,
	)
	return err
}

const shortIDTaken = `-- name: ShortIDTaken :one
SELECT EXISTS (SELECT 1 FROM nodes WHERE short_id = $1)
`

func (q *Queries) ShortIDTaken(ctx context.Context, shortID string) (bool, error) {
	row := q.db.QueryRow(ctx, shortIDTaken, shortID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const useJoinToken = `-- name: UseJoinToken :exec
UPDATE join_tokens SET used_at = now(), node_id = $2 WHERE id = $1
`

type UseJoinTokenParams struct {
	ID     pgtype.UUID
	NodeID pgtype.UUID
}

func (q *Queries) UseJoinToken(ctx context.Context, arg UseJoinTokenParams) error {
	_, err := q.db.Exec(ctx, useJoinToken, arg.ID, arg.NodeID)
	return err
}
