// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO oauth_accounts (user_id, provider, subject, email, email_verified, last_used_at)
VALUES ($1, $2, $3, $4, $5, now())
RETURNING id, user_id, provider, subject, email, email_verified, created_at, last_used_at
`

type CreateOAuthAccountParams struct {
	UserID        pgtype.UUID
	Provider      string
	Subject       string
	Email         string
	EmailVerified bool
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, createOAuthAccount,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.Email,
		arg.EmailVerified,
	)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createOAuthFlow = `-- name: CreateOAuthFlow :exec
INSERT INTO oauth_flows (state_hash, provider, verifier, nonce, session_id, expires_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateOAuthFlowParams struct {
	StateHash []byte
	Provider  string
	Verifier  string
	Nonce     string
	SessionID pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateOAuthFlow(ctx context.Context, arg CreateOAuthFlowParams) error {
	_, err := q.db.Exec(ctx, createOAuthFlow,
		arg.StateHash,
		arg.Provider,
		arg.Verifier,
		arg.Nonce,
		arg.SessionID,
		arg.ExpiresAt,
	)
	return err
}

const deleteOAuthAccount = `-- name: DeleteOAuthAccount :one
DELETE FROM oauth_accounts WHERE id = $1 AND user_id = $2 RETURNING id, user_id, provider, subject, email, email_verified, created_at, last_used_at
`

type DeleteOAuthAccountParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteOAuthAccount(ctx context.Context, arg DeleteOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, deleteOAuthAccount, arg.ID, arg.UserID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listOAuthAccounts = `-- name: ListOAuthAccounts :many
SELECT id, user_id, provider, subject, email, email_verified, created_at, last_used_at FROM oauth_accounts WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListOAuthAccounts(ctx context.Context, userID pgtype.UUID) ([]OauthAccount, error) {
	rows, err := q.db.Query(ctx, listOAuthAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthAccount
	for rows.Next() {
		var i OauthAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.Subject,
			&i.Email,
			&i.EmailVerified,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oAuthAccount = `-- name: OAuthAccount :one
SELECT id, user_id, provider, subject, email, email_verified, created_at, last_used_at FROM oauth_accounts WHERE provider = $1 AND subject = $2
`

type OAuthAccountParams struct {
	Provider string
	Subject  string
}

func (q *Queries) OAuthAccount(ctx context.Context, arg OAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, oAuthAccount, arg.Provider, arg.Subject)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const pruneOAuthFlows = `-- name: PruneOAuthFlows :exec
DELETE FROM oauth_flows WHERE expires_at < now()
`

func (q *Queries) PruneOAuthFlows(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneOAuthFlows)
	return err
}

const takeOAuthFlow = `-- name: TakeOAuthFlow :one
DELETE FROM oauth_flows WHERE state_hash = $1 RETURNING id, state_hash, provider, verifier, nonce, session_id, expires_at
`

func (q *Queries) TakeOAuthFlow(ctx context.Context, stateHash []byte) (OauthFlow, error) {
	row := q.db.QueryRow(ctx, takeOAuthFlow, stateHash)
	var i OauthFlow
	err := row.Scan(
		&i.ID,
		&i.StateHash,
		&i.Provider,
		&i.Verifier,
		&i.Nonce,
		&i.SessionID,
		&i.ExpiresAt,
	)
	return i, err
}

const useOAuthAccount = `-- name: UseOAuthAccount :exec
UPDATE oauth_accounts SET email = $2, email_verified = $3, last_used_at = now() WHERE id = $1
`

type UseOAuthAccountParams struct {
	ID            pgtype.UUID
	Email         string
	EmailVerified bool
}

func (q *Queries) UseOAuthAccount(ctx context.Context, arg UseOAuthAccountParams) error {
	_, err := q.db.Exec(ctx, useOAuthAccount, arg.ID, arg.Email, arg.EmailVerified)
	return err
}
