// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :exec
UPDATE org_invitations SET accepted_at = now() WHERE id = $1
`

func (q *Queries) AcceptInvitation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, acceptInvitation, id)
	return err
}

const addOrgMember = `-- name: AddOrgMember :exec
INSERT INTO org_members (org_id, user_id, role) VALUES ($1, $2, $3)
ON CONFLICT (org_id, user_id) DO NOTHING
`

type AddOrgMemberParams struct {
	OrgID  pgtype.UUID
	UserID pgtype.UUID
	Role   string
}

func (q *Queries) AddOrgMember(ctx context.Context, arg AddOrgMemberParams) error {
	_, err := q.db.Exec(ctx, addOrgMember, arg.OrgID, arg.UserID, arg.Role)
	return err
}

const countOwnedOrgs = `-- name: CountOwnedOrgs :one
SELECT count(*) FROM org_members WHERE user_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwnedOrgs(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnedOrgs, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingInvitations = `-- name: CountPendingInvitations :one
SELECT count(*) FROM org_invitations
WHERE org_id = $1 AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) CountPendingInvitations(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingInvitations, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO org_invitations (org_id, email, role, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, email, role, token_hash, invited_by, expires_at, accepted_at, revoked_at, created_at
`

type CreateInvitationParams struct {
	OrgID     pgtype.UUID
	Email     string
	Role      string
	TokenHash []byte
	InvitedBy pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (OrgInvitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.OrgID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i OrgInvitation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOrg = `-- name: GetOrg :one
SELECT id, name, created_at FROM orgs WHERE id = $1
`

func (q *Queries) GetOrg(ctx context.Context, id pgtype.UUID) (Org, error) {
	row := q.db.QueryRow(ctx, getOrg, id)
	var i Org
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const invitationByToken = `-- name: InvitationByToken :one
SELECT id, org_id, email, role, token_hash, invited_by, expires_at, accepted_at, revoked_at, created_at FROM org_invitations WHERE token_hash = $1 FOR UPDATE
`

func (q *Queries) InvitationByToken(ctx context.Context, tokenHash []byte) (OrgInvitation, error) {
	row := q.db.QueryRow(ctx, invitationByToken, tokenHash)
	var i OrgInvitation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const lockOrgOwners = `-- name: LockOrgOwners :many
SELECT user_id FROM org_members WHERE org_id = $1 AND role = 'owner' FOR UPDATE
`

// The org's owners, locked, so two changes can't remove the last one
// between them.
func (q *Queries) LockOrgOwners(ctx context.Context, orgID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, lockOrgOwners, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nodeServers = `-- name: NodeServers :many
SELECT server_id, name, state, egg_name FROM m_servers WHERE node_id = $1 ORDER BY name, server_id
`

type NodeServersRow struct {
	ServerID string
	Name     string
	State    string
	EggName  string
}

func (q *Queries) NodeServers(ctx context.Context, nodeID pgtype.UUID) ([]NodeServersRow, error) {
	rows, err := q.db.Query(ctx, nodeServers, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeServersRow
	for rows.Next() {
		var i NodeServersRow
		if err := rows.Scan(
			&i.ServerID,
			&i.Name,
			&i.State,
			&i.EggName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgMember = `-- name: OrgMember :one
SELECT org_id, user_id, role, created_at FROM org_members WHERE org_id = $1 AND user_id = $2
`

type OrgMemberParams struct {
	OrgID  pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) OrgMember(ctx context.Context, arg OrgMemberParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, orgMember, arg.OrgID, arg.UserID)
	var i OrgMember
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const orgMembers = `-- name: OrgMembers :many
SELECT m.user_id, m.role, m.created_at, u.email, u.name FROM org_members m
JOIN users u ON u.id = m.user_id
WHERE m.org_id = $1
ORDER BY m.created_at
`

type OrgMembersRow struct {
	UserID    pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
	Email     string
	Name      string
}

func (q *Queries) OrgMembers(ctx context.Context, orgID pgtype.UUID) ([]OrgMembersRow, error) {
	rows, err := q.db.Query(ctx, orgMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgMembersRow
	for rows.Next() {
		var i OrgMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgNodes = `-- name: OrgNodes :many
SELECT n.id, n.name, n.short_id, n.wings_version, n.last_seen_at, n.created_at,
       (c.node_id IS NOT NULL)::bool AS connected
FROM nodes n LEFT JOIN node_connections c ON c.node_id = n.id
WHERE n.org_id = $1 AND n.deleted_at IS NULL
ORDER BY n.created_at
`

type OrgNodesRow struct {
	ID           pgtype.UUID
	Name         string
	ShortID      string
	WingsVersion string
	LastSeenAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	Connected    bool
}

func (q *Queries) OrgNodes(ctx context.Context, orgID pgtype.UUID) ([]OrgNodesRow, error) {
	rows, err := q.db.Query(ctx, orgNodes, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgNodesRow
	for rows.Next() {
		var i OrgNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShortID,
			&i.WingsVersion,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.Connected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingInvitations = `-- name: PendingInvitations :many
SELECT id, org_id, email, role, token_hash, invited_by, expires_at, accepted_at, revoked_at, created_at FROM org_invitations
WHERE org_id = $1 AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at > now()
ORDER BY created_at
`

func (q *Queries) PendingInvitations(ctx context.Context, orgID pgtype.UUID) ([]OrgInvitation, error) {
	rows, err := q.db.Query(ctx, pendingInvitations, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgInvitation
	for rows.Next() {
		var i OrgInvitation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOrgMember = `-- name: RemoveOrgMember :execrows
DELETE FROM org_members WHERE org_id = $1 AND user_id = $2
`

type RemoveOrgMemberParams struct {
	OrgID  pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) RemoveOrgMember(ctx context.Context, arg RemoveOrgMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeOrgMember, arg.OrgID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renameOrg = `-- name: RenameOrg :exec
UPDATE orgs SET name = $2 WHERE id = $1
`

type RenameOrgParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) RenameOrg(ctx context.Context, arg RenameOrgParams) error {
	_, err := q.db.Exec(ctx, renameOrg, arg.ID, arg.Name)
	return err
}

const revokeInvitation = `-- name: RevokeInvitation :execrows
UPDATE org_invitations SET revoked_at = now()
WHERE id = $1 AND org_id = $2 AND accepted_at IS NULL AND revoked_at IS NULL
`

type RevokeInvitationParams struct {
	ID    pgtype.UUID
	OrgID pgtype.UUID
}

func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvitation, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setOrgMemberRole = `-- name: SetOrgMemberRole :execrows
UPDATE org_members SET role = $3 WHERE org_id = $1 AND user_id = $2
`

type SetOrgMemberRoleParams struct {
	OrgID  pgtype.UUID
	UserID pgtype.UUID
	Role   string
}

func (q *Queries) SetOrgMemberRole(ctx context.Context, arg SetOrgMemberRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, setOrgMemberRole, arg.OrgID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userGrantsInOrg = `-- name: UserGrantsInOrg :many
SELECT node_id, server_id, permissions FROM server_grants WHERE org_id = $1 AND user_id = $2
`

type UserGrantsInOrgParams struct {
	OrgID  pgtype.UUID
	UserID pgtype.UUID
}

type UserGrantsInOrgRow struct {
	NodeID      pgtype.UUID
	ServerID    string
	Permissions []string
}

// A member's server grants in an org.
func (q *Queries) UserGrantsInOrg(ctx context.Context, arg UserGrantsInOrgParams) ([]UserGrantsInOrgRow, error) {
	rows, err := q.db.Query(ctx, userGrantsInOrg, arg.OrgID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGrantsInOrgRow
	for rows.Next() {
		var i UserGrantsInOrgRow
		if err := rows.Scan(&i.NodeID, &i.ServerID, &i.Permissions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userOrgs = `-- name: UserOrgs :many
SELECT o.id, o.name, o.created_at, m.role FROM orgs o
JOIN org_members m ON m.org_id = o.id
WHERE m.user_id = $1
ORDER BY o.created_at
`

type UserOrgsRow struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	Role      string
}

func (q *Queries) UserOrgs(ctx context.Context, userID pgtype.UUID) ([]UserOrgsRow, error) {
	rows, err := q.db.Query(ctx, userOrgs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserOrgsRow
	for rows.Next() {
		var i UserOrgsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
