// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: passkeys.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPasskeys = `-- name: CountPasskeys :one
SELECT count(*) FROM passkeys WHERE user_id = $1
`

func (q *Queries) CountPasskeys(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPasskeys, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCeremony = `-- name: CreateCeremony :one
INSERT INTO webauthn_ceremonies (purpose, session_id, data, expires_at) VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateCeremonyParams struct {
	Purpose   string
	SessionID pgtype.UUID
	Data      []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateCeremony(ctx context.Context, arg CreateCeremonyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createCeremony,
		arg.Purpose,
		arg.SessionID,
		arg.Data,
		arg.ExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createPasskey = `-- name: CreatePasskey :one
INSERT INTO passkeys (user_id, credential_id, credential, name) VALUES ($1, $2, $3, $4)
RETURNING id, user_id, credential_id, credential, name, created_at, last_used_at
`

type CreatePasskeyParams struct {
	UserID       pgtype.UUID
	CredentialID []byte
	Credential   []byte
	Name         string
}

func (q *Queries) CreatePasskey(ctx context.Context, arg CreatePasskeyParams) (Passkey, error) {
	row := q.db.QueryRow(ctx, createPasskey,
		arg.UserID,
		arg.CredentialID,
		arg.Credential,
		arg.Name,
	)
	var i Passkey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.Credential,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deletePasskey = `-- name: DeletePasskey :one
DELETE FROM passkeys WHERE id = $1 AND user_id = $2 RETURNING id, user_id, credential_id, credential, name, created_at, last_used_at
`

type DeletePasskeyParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeletePasskey(ctx context.Context, arg DeletePasskeyParams) (Passkey, error) {
	row := q.db.QueryRow(ctx, deletePasskey, arg.ID, arg.UserID)
	var i Passkey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.Credential,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getUserByWebAuthnHandle = `-- name: GetUserByWebAuthnHandle :one
SELECT id, email, email_verified_at, name, created_at, webauthn_handle, totp_secret, totp_enabled_at, totp_last_step, theme FROM users WHERE webauthn_handle = $1
`

func (q *Queries) GetUserByWebAuthnHandle(ctx context.Context, webauthnHandle []byte) (User, error) {
	row := q.db.QueryRow(ctx, getUserByWebAuthnHandle, webauthnHandle)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Name,
		&i.CreatedAt,
		&i.WebauthnHandle,
		&i.TotpSecret,
		&i.TotpEnabledAt,
		&i.TotpLastStep,
		&i.Theme,
	)
	return i, err
}

const listPasskeys = `-- name: ListPasskeys :many
SELECT id, user_id, credential_id, credential, name, created_at, last_used_at FROM passkeys WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListPasskeys(ctx context.Context, userID pgtype.UUID) ([]Passkey, error) {
	rows, err := q.db.Query(ctx, listPasskeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Passkey
	for rows.Next() {
		var i Passkey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.Credential,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const passkeyByCredentialID = `-- name: PasskeyByCredentialID :one
SELECT id, user_id, credential_id, credential, name, created_at, last_used_at FROM passkeys WHERE credential_id = $1 FOR UPDATE
`

// Locked: signing in updates the counter.
func (q *Queries) PasskeyByCredentialID(ctx context.Context, credentialID []byte) (Passkey, error) {
	row := q.db.QueryRow(ctx, passkeyByCredentialID, credentialID)
	var i Passkey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.Credential,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const pruneCeremonies = `-- name: PruneCeremonies :exec
DELETE FROM webauthn_ceremonies WHERE expires_at < now()
`

func (q *Queries) PruneCeremonies(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneCeremonies)
	return err
}

const renamePasskey = `-- name: RenamePasskey :execrows
UPDATE passkeys SET name = $3 WHERE id = $1 AND user_id = $2
`

type RenamePasskeyParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	Name   string
}

func (q *Queries) RenamePasskey(ctx context.Context, arg RenamePasskeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, renamePasskey, arg.ID, arg.UserID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setWebAuthnHandle = `-- name: SetWebAuthnHandle :one
UPDATE users SET webauthn_handle = COALESCE(webauthn_handle, $2::bytea) WHERE id = $1
RETURNING webauthn_handle
`

type SetWebAuthnHandleParams struct {
	ID     pgtype.UUID
	Handle []byte
}

// The user's passkey handle, made the first time it's needed.
func (q *Queries) SetWebAuthnHandle(ctx context.Context, arg SetWebAuthnHandleParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, setWebAuthnHandle, arg.ID, arg.Handle)
	var webauthn_handle []byte
	err := row.Scan(&webauthn_handle)
	return webauthn_handle, err
}

const takeCeremony = `-- name: TakeCeremony :one
DELETE FROM webauthn_ceremonies WHERE id = $1 RETURNING id, purpose, session_id, data, expires_at
`

// Ceremonies are single use: taking one deletes it.
func (q *Queries) TakeCeremony(ctx context.Context, id pgtype.UUID) (WebauthnCeremony, error) {
	row := q.db.QueryRow(ctx, takeCeremony, id)
	var i WebauthnCeremony
	err := row.Scan(
		&i.ID,
		&i.Purpose,
		&i.SessionID,
		&i.Data,
		&i.ExpiresAt,
	)
	return i, err
}

const usePasskey = `-- name: UsePasskey :exec
UPDATE passkeys SET credential = $2, last_used_at = now() WHERE id = $1
`

type UsePasskeyParams struct {
	ID         pgtype.UUID
	Credential []byte
}

func (q *Queries) UsePasskey(ctx context.Context, arg UsePasskeyParams) error {
	_, err := q.db.Exec(ctx, usePasskey, arg.ID, arg.Credential)
	return err
}
