// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rollouts.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeRollout = `-- name: ActiveRollout :one
SELECT id, version, state, stage, stage_started_at, reason, created_at, finished_at FROM wings_rollouts WHERE state IN ('running', 'paused')
`

func (q *Queries) ActiveRollout(ctx context.Context) (WingsRollout, error) {
	row := q.db.QueryRow(ctx, activeRollout)
	var i WingsRollout
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.State,
		&i.Stage,
		&i.StageStartedAt,
		&i.Reason,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const addRolloutNode = `-- name: AddRolloutNode :exec
INSERT INTO rollout_nodes (rollout_id, node_id, stage, status, from_version, error, finished_at)
VALUES ($1, $2, $3, $4, $5, $6, CASE WHEN $4 = 'sent' THEN NULL ELSE now() END)
`

type AddRolloutNodeParams struct {
	RolloutID   pgtype.UUID
	NodeID      pgtype.UUID
	Stage       int32
	Status      string
	FromVersion string
	Error       string
}

func (q *Queries) AddRolloutNode(ctx context.Context, arg AddRolloutNodeParams) error {
	_, err := q.db.Exec(ctx, addRolloutNode,
		arg.RolloutID,
		arg.NodeID,
		arg.Stage,
		arg.Status,
		arg.FromVersion,
		arg.Error,
	)
	return err
}

const advanceRollout = `-- name: AdvanceRollout :exec
UPDATE wings_rollouts SET stage = stage + 1, stage_started_at = now() WHERE id = $1
`

func (q *Queries) AdvanceRollout(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, advanceRollout, id)
	return err
}

const createRollout = `-- name: CreateRollout :one
INSERT INTO wings_rollouts (version) VALUES ($1) RETURNING id, version, state, stage, stage_started_at, reason, created_at, finished_at
`

func (q *Queries) CreateRollout(ctx context.Context, version string) (WingsRollout, error) {
	row := q.db.QueryRow(ctx, createRollout, version)
	var i WingsRollout
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.State,
		&i.Stage,
		&i.StageStartedAt,
		&i.Reason,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishRolloutNode = `-- name: FinishRolloutNode :exec
UPDATE rollout_nodes SET status = $3, error = $4, finished_at = now()
WHERE rollout_id = $1 AND node_id = $2
`

type FinishRolloutNodeParams struct {
	RolloutID pgtype.UUID
	NodeID    pgtype.UUID
	Status    string
	Error     string
}

func (q *Queries) FinishRolloutNode(ctx context.Context, arg FinishRolloutNodeParams) error {
	_, err := q.db.Exec(ctx, finishRolloutNode,
		arg.RolloutID,
		arg.NodeID,
		arg.Status,
		arg.Error,
	)
	return err
}

const latestRollout = `-- name: LatestRollout :one
SELECT id, version, state, stage, stage_started_at, reason, created_at, finished_at FROM wings_rollouts ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) LatestRollout(ctx context.Context) (WingsRollout, error) {
	row := q.db.QueryRow(ctx, latestRollout)
	var i WingsRollout
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.State,
		&i.Stage,
		&i.StageStartedAt,
		&i.Reason,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const rolloutCandidates = `-- name: RolloutCandidates :many
SELECT n.id, n.wings_version,
       EXISTS (SELECT 1 FROM node_connections c JOIN panel_instances i ON i.id = c.instance_id
               WHERE c.node_id = n.id AND i.seen_at > now() - interval '20 seconds') AS connected
FROM nodes n
WHERE n.deleted_at IS NULL AND n.key_revoked_at IS NULL
`

type RolloutCandidatesRow struct {
	ID           pgtype.UUID
	WingsVersion string
	Connected    bool
}

// Every node that could be updated, with its version and whether an
// instance holds its connection now.
func (q *Queries) RolloutCandidates(ctx context.Context) ([]RolloutCandidatesRow, error) {
	rows, err := q.db.Query(ctx, rolloutCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RolloutCandidatesRow
	for rows.Next() {
		var i RolloutCandidatesRow
		if err := rows.Scan(&i.ID, &i.WingsVersion, &i.Connected); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rolloutNodes = `-- name: RolloutNodes :many
SELECT rollout_id, node_id, stage, status, from_version, error, sent_at, finished_at FROM rollout_nodes WHERE rollout_id = $1
`

func (q *Queries) RolloutNodes(ctx context.Context, rolloutID pgtype.UUID) ([]RolloutNode, error) {
	rows, err := q.db.Query(ctx, rolloutNodes, rolloutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RolloutNode
	for rows.Next() {
		var i RolloutNode
		if err := rows.Scan(
			&i.RolloutID,
			&i.NodeID,
			&i.Stage,
			&i.Status,
			&i.FromVersion,
			&i.Error,
			&i.SentAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRolloutState = `-- name: SetRolloutState :exec
UPDATE wings_rollouts
SET state = $2, reason = $3,
    finished_at = CASE WHEN $2 IN ('halted', 'done', 'cancelled') THEN now() END
WHERE id = $1
`

type SetRolloutStateParams struct {
	ID     pgtype.UUID
	State  string
	Reason string
}

func (q *Queries) SetRolloutState(ctx context.Context, arg SetRolloutStateParams) error {
	_, err := q.db.Exec(ctx, setRolloutState, arg.ID, arg.State, arg.Reason)
	return err
}
