// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ssh_keys.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addSSHKey = `-- name: AddSSHKey :one
INSERT INTO ssh_keys (user_id, name, public_key, fingerprint) VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, public_key, fingerprint, created_at, last_used_at
`

type AddSSHKeyParams struct {
	UserID      pgtype.UUID
	Name        string
	PublicKey   []byte
	Fingerprint string
}

func (q *Queries) AddSSHKey(ctx context.Context, arg AddSSHKeyParams) (SshKey, error) {
	row := q.db.QueryRow(ctx, addSSHKey,
		arg.UserID,
		arg.Name,
		arg.PublicKey,
		arg.Fingerprint,
	)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PublicKey,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const countSSHKeys = `-- name: CountSSHKeys :one
SELECT count(*) FROM ssh_keys WHERE user_id = $1
`

func (q *Queries) CountSSHKeys(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSSHKeys, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSSHKey = `-- name: DeleteSSHKey :one
DELETE FROM ssh_keys WHERE id = $1 AND user_id = $2 RETURNING id, user_id, name, public_key, fingerprint, created_at, last_used_at
`

type DeleteSSHKeyParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteSSHKey(ctx context.Context, arg DeleteSSHKeyParams) (SshKey, error) {
	row := q.db.QueryRow(ctx, deleteSSHKey, arg.ID, arg.UserID)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PublicKey,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getUserBySFTPUsername = `-- name: GetUserBySFTPUsername :one
SELECT id, email, email_verified_at, name, created_at, webauthn_handle, totp_secret, totp_enabled_at, totp_last_step, sftp_username, theme FROM users WHERE sftp_username = $1
`

func (q *Queries) GetUserBySFTPUsername(ctx context.Context, sftpUsername pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySFTPUsername, sftpUsername)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Name,
		&i.CreatedAt,
		&i.WebauthnHandle,
		&i.TotpSecret,
		&i.TotpEnabledAt,
		&i.TotpLastStep,
		&i.SftpUsername,
		&i.Theme,
	)
	return i, err
}

const listSSHKeys = `-- name: ListSSHKeys :many
SELECT id, user_id, name, public_key, fingerprint, created_at, last_used_at FROM ssh_keys WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListSSHKeys(ctx context.Context, userID pgtype.UUID) ([]SshKey, error) {
	rows, err := q.db.Query(ctx, listSSHKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SshKey
	for rows.Next() {
		var i SshKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.PublicKey,
			&i.Fingerprint,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sSHKeyByFingerprint = `-- name: SSHKeyByFingerprint :one
SELECT id, user_id, name, public_key, fingerprint, created_at, last_used_at FROM ssh_keys WHERE user_id = $1 AND fingerprint = $2
`

type SSHKeyByFingerprintParams struct {
	UserID      pgtype.UUID
	Fingerprint string
}

func (q *Queries) SSHKeyByFingerprint(ctx context.Context, arg SSHKeyByFingerprintParams) (SshKey, error) {
	row := q.db.QueryRow(ctx, sSHKeyByFingerprint, arg.UserID, arg.Fingerprint)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PublicKey,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const setSFTPUsername = `-- name: SetSFTPUsername :execrows
UPDATE users SET sftp_username = $2 WHERE id = $1 AND sftp_username IS NULL
`

type SetSFTPUsernameParams struct {
	ID           pgtype.UUID
	SftpUsername pgtype.Text
}

func (q *Queries) SetSFTPUsername(ctx context.Context, arg SetSFTPUsernameParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSFTPUsername, arg.ID, arg.SftpUsername)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const useSSHKey = `-- name: UseSSHKey :exec
UPDATE ssh_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) UseSSHKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, useSSHKey, id)
	return err
}
