// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: totp.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRecoveryCode = `-- name: AddRecoveryCode :exec
INSERT INTO recovery_codes (user_id, code_hash) VALUES ($1, $2)
`

type AddRecoveryCodeParams struct {
	UserID   pgtype.UUID
	CodeHash []byte
}

func (q *Queries) AddRecoveryCode(ctx context.Context, arg AddRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, addRecoveryCode, arg.UserID, arg.CodeHash)
	return err
}

const countPendingSigninAttempt = `-- name: CountPendingSigninAttempt :exec
UPDATE pending_signins SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) CountPendingSigninAttempt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, countPendingSigninAttempt, id)
	return err
}

const countRecoveryCodes = `-- name: CountRecoveryCodes :one
SELECT count(*) FROM recovery_codes WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) CountRecoveryCodes(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRecoveryCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPendingSignin = `-- name: CreatePendingSignin :exec
INSERT INTO pending_signins (user_id, token_hash, expires_at) VALUES ($1, $2, $3)
`

type CreatePendingSigninParams struct {
	UserID    pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreatePendingSignin(ctx context.Context, arg CreatePendingSigninParams) error {
	_, err := q.db.Exec(ctx, createPendingSignin, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const deletePendingSignin = `-- name: DeletePendingSignin :exec
DELETE FROM pending_signins WHERE id = $1
`

func (q *Queries) DeletePendingSignin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePendingSignin, id)
	return err
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodes, userID)
	return err
}

const deleteTOTPSetup = `-- name: DeleteTOTPSetup :exec
DELETE FROM totp_setups WHERE user_id = $1
`

func (q *Queries) DeleteTOTPSetup(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTOTPSetup, userID)
	return err
}

const disableTOTP = `-- name: DisableTOTP :exec
UPDATE users SET totp_secret = NULL, totp_enabled_at = NULL, totp_last_step = 0 WHERE id = $1
`

func (q *Queries) DisableTOTP(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disableTOTP, id)
	return err
}

const enableTOTP = `-- name: EnableTOTP :exec
UPDATE users SET totp_secret = $2, totp_enabled_at = now(), totp_last_step = $3 WHERE id = $1
`

type EnableTOTPParams struct {
	ID           pgtype.UUID
	TotpSecret   []byte
	TotpLastStep int64
}

func (q *Queries) EnableTOTP(ctx context.Context, arg EnableTOTPParams) error {
	_, err := q.db.Exec(ctx, enableTOTP, arg.ID, arg.TotpSecret, arg.TotpLastStep)
	return err
}

const lockUserTOTP = `-- name: LockUserTOTP :one
SELECT totp_secret, totp_last_step FROM users WHERE id = $1 FOR UPDATE
`

type LockUserTOTPRow struct {
	TotpSecret   []byte
	TotpLastStep int64
}

// The user's TOTP state, locked so a code's time step is used once.
func (q *Queries) LockUserTOTP(ctx context.Context, id pgtype.UUID) (LockUserTOTPRow, error) {
	row := q.db.QueryRow(ctx, lockUserTOTP, id)
	var i LockUserTOTPRow
	err := row.Scan(&i.TotpSecret, &i.TotpLastStep)
	return i, err
}

const pendingSigninByToken = `-- name: PendingSigninByToken :one
SELECT id, user_id, token_hash, attempts, expires_at, created_at FROM pending_signins WHERE token_hash = $1 FOR UPDATE
`

func (q *Queries) PendingSigninByToken(ctx context.Context, tokenHash []byte) (PendingSignin, error) {
	row := q.db.QueryRow(ctx, pendingSigninByToken, tokenHash)
	var i PendingSignin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const prunePending = `-- name: PrunePending :exec
DELETE FROM pending_signins WHERE expires_at < now()
`

func (q *Queries) PrunePending(ctx context.Context) error {
	_, err := q.db.Exec(ctx, prunePending)
	return err
}

const pruneTOTPSetups = `-- name: PruneTOTPSetups :exec
DELETE FROM totp_setups WHERE expires_at < now()
`

func (q *Queries) PruneTOTPSetups(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneTOTPSetups)
	return err
}

const saveTOTPSetup = `-- name: SaveTOTPSetup :exec
INSERT INTO totp_setups (user_id, secret, expires_at) VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE SET secret = excluded.secret, expires_at = excluded.expires_at
`

type SaveTOTPSetupParams struct {
	UserID    pgtype.UUID
	Secret    []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) SaveTOTPSetup(ctx context.Context, arg SaveTOTPSetupParams) error {
	_, err := q.db.Exec(ctx, saveTOTPSetup, arg.UserID, arg.Secret, arg.ExpiresAt)
	return err
}

const setTOTPStep = `-- name: SetTOTPStep :exec
UPDATE users SET totp_last_step = $2 WHERE id = $1
`

type SetTOTPStepParams struct {
	ID           pgtype.UUID
	TotpLastStep int64
}

func (q *Queries) SetTOTPStep(ctx context.Context, arg SetTOTPStepParams) error {
	_, err := q.db.Exec(ctx, setTOTPStep, arg.ID, arg.TotpLastStep)
	return err
}

const takeTOTPSetup = `-- name: TakeTOTPSetup :one
SELECT user_id, secret, expires_at FROM totp_setups WHERE user_id = $1 FOR UPDATE
`

func (q *Queries) TakeTOTPSetup(ctx context.Context, userID pgtype.UUID) (TotpSetup, error) {
	row := q.db.QueryRow(ctx, takeTOTPSetup, userID)
	var i TotpSetup
	err := row.Scan(&i.UserID, &i.Secret, &i.ExpiresAt)
	return i, err
}

const useRecoveryCode = `-- name: UseRecoveryCode :execrows
UPDATE recovery_codes SET used_at = now() WHERE user_id = $1 AND code_hash = $2 AND used_at IS NULL
`

type UseRecoveryCodeParams struct {
	UserID   pgtype.UUID
	CodeHash []byte
}

func (q *Queries) UseRecoveryCode(ctx context.Context, arg UseRecoveryCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, useRecoveryCode, arg.UserID, arg.CodeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
