// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package store

import (
	"context"
)

const deleteAllTrustedKeys = `-- name: DeleteAllTrustedKeys :execrows
DELETE FROM trusted_keys
`

func (q *Queries) DeleteAllTrustedKeys(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAllTrustedKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishAudit = `-- name: FinishAudit :exec
UPDATE audit_log SET outcome = ?, detail = ? WHERE id = ?
`

type FinishAuditParams struct {
	Outcome string
	Detail  string
	ID      int64
}

func (q *Queries) FinishAudit(ctx context.Context, arg FinishAuditParams) error {
	_, err := q.db.ExecContext(ctx, finishAudit, arg.Outcome, arg.Detail, arg.ID)
	return err
}

const getAudit = `-- name: GetAudit :one
SELECT id, at, command_id, "action", server_id, user_id, credential_id, key_name, command_hash, outcome, detail FROM audit_log WHERE id = ?
`

func (q *Queries) GetAudit(ctx context.Context, id int64) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, getAudit, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.At,
		&i.CommandID,
		&i.Action,
		&i.ServerID,
		&i.UserID,
		&i.CredentialID,
		&i.KeyName,
		&i.CommandHash,
		&i.Outcome,
		&i.Detail,
	)
	return i, err
}

const insertAudit = `-- name: InsertAudit :one
INSERT INTO audit_log (at, command_id, action, server_id, user_id, credential_id, key_name, command_hash, outcome, detail)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertAuditParams struct {
	At           int64
	CommandID    string
	Action       string
	ServerID     string
	UserID       string
	CredentialID []byte
	KeyName      string
	CommandHash  []byte
	Outcome      string
	Detail       string
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertAudit,
		arg.At,
		arg.CommandID,
		arg.Action,
		arg.ServerID,
		arg.UserID,
		arg.CredentialID,
		arg.KeyName,
		arg.CommandHash,
		arg.Outcome,
		arg.Detail,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const interruptedAudit = `-- name: InterruptedAudit :execrows
UPDATE audit_log SET outcome = 'failed', detail = 'interrupted: Wings stopped while running it' WHERE outcome = 'running'
`

func (q *Queries) InterruptedAudit(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, interruptedAudit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAudit = `-- name: ListAudit :many
SELECT id, at, command_id, "action", server_id, user_id, credential_id, key_name, command_hash, outcome, detail FROM audit_log WHERE at >= ?1 ORDER BY id DESC LIMIT ?2
`

type ListAuditParams struct {
	Since int64
	Limit int64
}

func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAudit, arg.Since, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.CommandID,
			&i.Action,
			&i.ServerID,
			&i.UserID,
			&i.CredentialID,
			&i.KeyName,
			&i.CommandHash,
			&i.Outcome,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditAfter = `-- name: ListAuditAfter :many
SELECT id, at, command_id, "action", server_id, user_id, credential_id, key_name, command_hash, outcome, detail FROM audit_log WHERE id > ? ORDER BY id LIMIT ?
`

type ListAuditAfterParams struct {
	ID    int64
	Limit int64
}

func (q *Queries) ListAuditAfter(ctx context.Context, arg ListAuditAfterParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditAfter, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.CommandID,
			&i.Action,
			&i.ServerID,
			&i.UserID,
			&i.CredentialID,
			&i.KeyName,
			&i.CommandHash,
			&i.Outcome,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAudit = `-- name: PruneAudit :execrows
DELETE FROM audit_log WHERE at < ?
`

func (q *Queries) PruneAudit(ctx context.Context, at int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneAudit, at)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
