// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backups.sql

package store

import (
	"context"
	"database/sql"
)

const countDestinationTargets = `-- name: CountDestinationTargets :one
SELECT COUNT(*) FROM backup_targets WHERE destination_id = ?
`

func (q *Queries) CountDestinationTargets(ctx context.Context, destinationID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDestinationTargets, destinationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBackupDestination = `-- name: DeleteBackupDestination :exec
DELETE FROM backup_destinations WHERE id = ?
`

func (q *Queries) DeleteBackupDestination(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBackupDestination, id)
	return err
}

const deleteBackupRow = `-- name: DeleteBackupRow :exec
DELETE FROM backups WHERE id = ?
`

func (q *Queries) DeleteBackupRow(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBackupRow, id)
	return err
}

const deleteBackupTargets = `-- name: DeleteBackupTargets :exec
DELETE FROM backup_targets WHERE server_id = ?
`

func (q *Queries) DeleteBackupTargets(ctx context.Context, serverID string) error {
	_, err := q.db.ExecContext(ctx, deleteBackupTargets, serverID)
	return err
}

const destinationFailed = `-- name: DestinationFailed :exec
UPDATE backup_destinations SET last_error = ?, last_error_at = ? WHERE id = ?
`

type DestinationFailedParams struct {
	LastError   string
	LastErrorAt sql.NullInt64
	ID          string
}

func (q *Queries) DestinationFailed(ctx context.Context, arg DestinationFailedParams) error {
	_, err := q.db.ExecContext(ctx, destinationFailed, arg.LastError, arg.LastErrorAt, arg.ID)
	return err
}

const destinationWorked = `-- name: DestinationWorked :exec
UPDATE backup_destinations SET last_ok_at = ? WHERE id = ?
`

type DestinationWorkedParams struct {
	LastOkAt sql.NullInt64
	ID       string
}

func (q *Queries) DestinationWorked(ctx context.Context, arg DestinationWorkedParams) error {
	_, err := q.db.ExecContext(ctx, destinationWorked, arg.LastOkAt, arg.ID)
	return err
}

const expiredBackups = `-- name: ExpiredBackups :many
SELECT id, server_id, destination_id, kind, status, locked, snapshot_id, size, files, uploaded, warning, error, job_id, created_by, created_at, finished_at, expires_at FROM backups
WHERE locked = 0 AND ((expires_at IS NOT NULL AND expires_at <= ?1)
    OR (status = 'failed' AND created_at <= ?2))
`

type ExpiredBackupsParams struct {
	Now          sql.NullInt64
	FailedBefore int64
}

// Safety backups past their expiry, and failed backups older than the cutoff.
func (q *Queries) ExpiredBackups(ctx context.Context, arg ExpiredBackupsParams) ([]Backup, error) {
	rows, err := q.db.QueryContext(ctx, expiredBackups, arg.Now, arg.FailedBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Backup
	for rows.Next() {
		var i Backup
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.DestinationID,
			&i.Kind,
			&i.Status,
			&i.Locked,
			&i.SnapshotID,
			&i.Size,
			&i.Files,
			&i.Uploaded,
			&i.Warning,
			&i.Error,
			&i.JobID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failBackup = `-- name: FailBackup :exec
UPDATE backups SET status = 'failed', error = ?, finished_at = ? WHERE id = ?
`

type FailBackupParams struct {
	Error      string
	FinishedAt sql.NullInt64
	ID         string
}

func (q *Queries) FailBackup(ctx context.Context, arg FailBackupParams) error {
	_, err := q.db.ExecContext(ctx, failBackup, arg.Error, arg.FinishedAt, arg.ID)
	return err
}

const finishBackup = `-- name: FinishBackup :exec
UPDATE backups
SET status = 'ok', snapshot_id = ?, size = ?, files = ?, uploaded = ?, warning = ?, error = '', finished_at = ?
WHERE id = ?
`

type FinishBackupParams struct {
	SnapshotID string
	Size       int64
	Files      int64
	Uploaded   int64
	Warning    string
	FinishedAt sql.NullInt64
	ID         string
}

func (q *Queries) FinishBackup(ctx context.Context, arg FinishBackupParams) error {
	_, err := q.db.ExecContext(ctx, finishBackup,
		arg.SnapshotID,
		arg.Size,
		arg.Files,
		arg.Uploaded,
		arg.Warning,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const getBackup = `-- name: GetBackup :one
SELECT id, server_id, destination_id, kind, status, locked, snapshot_id, size, files, uploaded, warning, error, job_id, created_by, created_at, finished_at, expires_at FROM backups WHERE id = ?
`

func (q *Queries) GetBackup(ctx context.Context, id string) (Backup, error) {
	row := q.db.QueryRowContext(ctx, getBackup, id)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.DestinationID,
		&i.Kind,
		&i.Status,
		&i.Locked,
		&i.SnapshotID,
		&i.Size,
		&i.Files,
		&i.Uploaded,
		&i.Warning,
		&i.Error,
		&i.JobID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getBackupDestination = `-- name: GetBackupDestination :one
SELECT id, name, type, config, upload_limit, version, created_at, updated_at, last_ok_at, last_error, last_error_at, size, size_at FROM backup_destinations WHERE id = ?
`

func (q *Queries) GetBackupDestination(ctx context.Context, id string) (BackupDestination, error) {
	row := q.db.QueryRowContext(ctx, getBackupDestination, id)
	var i BackupDestination
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.UploadLimit,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastOkAt,
		&i.LastError,
		&i.LastErrorAt,
		&i.Size,
		&i.SizeAt,
	)
	return i, err
}

const getBackupPolicy = `-- name: GetBackupPolicy :one
SELECT server_id, destination_id, keep_last, keep_daily, keep_weekly, keep_monthly, "ignore", version, updated_at FROM backup_policies WHERE server_id = ?
`

func (q *Queries) GetBackupPolicy(ctx context.Context, serverID string) (BackupPolicy, error) {
	row := q.db.QueryRowContext(ctx, getBackupPolicy, serverID)
	var i BackupPolicy
	err := row.Scan(
		&i.ServerID,
		&i.DestinationID,
		&i.KeepLast,
		&i.KeepDaily,
		&i.KeepWeekly,
		&i.KeepMonthly,
		&i.Ignore,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobBackup = `-- name: GetJobBackup :one
SELECT id, server_id, destination_id, kind, status, locked, snapshot_id, size, files, uploaded, warning, error, job_id, created_by, created_at, finished_at, expires_at FROM backups WHERE job_id = ? AND kind = ? ORDER BY created_at DESC LIMIT 1
`

type GetJobBackupParams struct {
	JobID string
	Kind  string
}

// The backup a job takes for itself (a safety or final backup), so a
// resumed job finds it again.
func (q *Queries) GetJobBackup(ctx context.Context, arg GetJobBackupParams) (Backup, error) {
	row := q.db.QueryRowContext(ctx, getJobBackup, arg.JobID, arg.Kind)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.DestinationID,
		&i.Kind,
		&i.Status,
		&i.Locked,
		&i.SnapshotID,
		&i.Size,
		&i.Files,
		&i.Uploaded,
		&i.Warning,
		&i.Error,
		&i.JobID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertBackup = `-- name: InsertBackup :exec
INSERT INTO backups (id, server_id, destination_id, kind, locked, job_id, created_by, created_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertBackupParams struct {
	ID            string
	ServerID      string
	DestinationID string
	Kind          string
	Locked        int64
	JobID         string
	CreatedBy     string
	CreatedAt     int64
	ExpiresAt     sql.NullInt64
}

func (q *Queries) InsertBackup(ctx context.Context, arg InsertBackupParams) error {
	_, err := q.db.ExecContext(ctx, insertBackup,
		arg.ID,
		arg.ServerID,
		arg.DestinationID,
		arg.Kind,
		arg.Locked,
		arg.JobID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertBackupDestination = `-- name: InsertBackupDestination :exec
INSERT INTO backup_destinations (id, name, type, config, upload_limit, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertBackupDestinationParams struct {
	ID          string
	Name        string
	Type        string
	Config      string
	UploadLimit int64
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) InsertBackupDestination(ctx context.Context, arg InsertBackupDestinationParams) error {
	_, err := q.db.ExecContext(ctx, insertBackupDestination,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.UploadLimit,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertBackupTarget = `-- name: InsertBackupTarget :exec
INSERT INTO backup_targets (server_id, destination_id, position, keep_last, keep_daily, keep_weekly, keep_monthly)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertBackupTargetParams struct {
	ServerID      string
	DestinationID string
	Position      int64
	KeepLast      int64
	KeepDaily     int64
	KeepWeekly    int64
	KeepMonthly   int64
}

func (q *Queries) InsertBackupTarget(ctx context.Context, arg InsertBackupTargetParams) error {
	_, err := q.db.ExecContext(ctx, insertBackupTarget,
		arg.ServerID,
		arg.DestinationID,
		arg.Position,
		arg.KeepLast,
		arg.KeepDaily,
		arg.KeepWeekly,
		arg.KeepMonthly,
	)
	return err
}

const listBackupDestinations = `-- name: ListBackupDestinations :many
SELECT id, name, type, config, upload_limit, version, created_at, updated_at, last_ok_at, last_error, last_error_at, size, size_at FROM backup_destinations ORDER BY id != 'local', created_at, id
`

func (q *Queries) ListBackupDestinations(ctx context.Context) ([]BackupDestination, error) {
	rows, err := q.db.QueryContext(ctx, listBackupDestinations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BackupDestination
	for rows.Next() {
		var i BackupDestination
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.UploadLimit,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastOkAt,
			&i.LastError,
			&i.LastErrorAt,
			&i.Size,
			&i.SizeAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackupTargets = `-- name: ListBackupTargets :many
SELECT server_id, destination_id, position, keep_last, keep_daily, keep_weekly, keep_monthly FROM backup_targets WHERE server_id = ? ORDER BY position
`

func (q *Queries) ListBackupTargets(ctx context.Context, serverID string) ([]BackupTarget, error) {
	rows, err := q.db.QueryContext(ctx, listBackupTargets, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BackupTarget
	for rows.Next() {
		var i BackupTarget
		if err := rows.Scan(
			&i.ServerID,
			&i.DestinationID,
			&i.Position,
			&i.KeepLast,
			&i.KeepDaily,
			&i.KeepWeekly,
			&i.KeepMonthly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackups = `-- name: ListBackups :many
SELECT id, server_id, destination_id, kind, status, locked, snapshot_id, size, files, uploaded, warning, error, job_id, created_by, created_at, finished_at, expires_at FROM backups WHERE (?1 = '' OR server_id = ?1)
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListBackups(ctx context.Context, serverID interface{}) ([]Backup, error) {
	rows, err := q.db.QueryContext(ctx, listBackups, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Backup
	for rows.Next() {
		var i Backup
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.DestinationID,
			&i.Kind,
			&i.Status,
			&i.Locked,
			&i.SnapshotID,
			&i.Size,
			&i.Files,
			&i.Uploaded,
			&i.Warning,
			&i.Error,
			&i.JobID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDestinationBackups = `-- name: ListDestinationBackups :many
SELECT id, server_id, destination_id, kind, status, locked, snapshot_id, size, files, uploaded, warning, error, job_id, created_by, created_at, finished_at, expires_at FROM backups WHERE destination_id = ? AND server_id = ?
`

type ListDestinationBackupsParams struct {
	DestinationID string
	ServerID      string
}

func (q *Queries) ListDestinationBackups(ctx context.Context, arg ListDestinationBackupsParams) ([]Backup, error) {
	rows, err := q.db.QueryContext(ctx, listDestinationBackups, arg.DestinationID, arg.ServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Backup
	for rows.Next() {
		var i Backup
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.DestinationID,
			&i.Kind,
			&i.Status,
			&i.Locked,
			&i.SnapshotID,
			&i.Size,
			&i.Files,
			&i.Uploaded,
			&i.Warning,
			&i.Error,
			&i.JobID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBackupLocked = `-- name: SetBackupLocked :exec
UPDATE backups SET locked = ? WHERE id = ?
`

type SetBackupLockedParams struct {
	Locked int64
	ID     string
}

func (q *Queries) SetBackupLocked(ctx context.Context, arg SetBackupLockedParams) error {
	_, err := q.db.ExecContext(ctx, setBackupLocked, arg.Locked, arg.ID)
	return err
}

const setBackupRunning = `-- name: SetBackupRunning :exec
UPDATE backups SET status = 'running', error = '' WHERE id = ?
`

func (q *Queries) SetBackupRunning(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setBackupRunning, id)
	return err
}

const setDestinationSize = `-- name: SetDestinationSize :exec
UPDATE backup_destinations SET size = ?, size_at = ? WHERE id = ?
`

type SetDestinationSizeParams struct {
	Size   sql.NullInt64
	SizeAt sql.NullInt64
	ID     string
}

func (q *Queries) SetDestinationSize(ctx context.Context, arg SetDestinationSizeParams) error {
	_, err := q.db.ExecContext(ctx, setDestinationSize, arg.Size, arg.SizeAt, arg.ID)
	return err
}

const updateBackupDestination = `-- name: UpdateBackupDestination :exec

UPDATE backup_destinations SET name = ?, config = ?, upload_limit = ?, version = version + 1, updated_at = ? WHERE id = ?
`

type UpdateBackupDestinationParams struct {
	Name        string
	Config      string
	UploadLimit int64
	UpdatedAt   int64
	ID          string
}

// local first
func (q *Queries) UpdateBackupDestination(ctx context.Context, arg UpdateBackupDestinationParams) error {
	_, err := q.db.ExecContext(ctx, updateBackupDestination,
		arg.Name,
		arg.Config,
		arg.UploadLimit,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertBackupPolicy = `-- name: UpsertBackupPolicy :exec
INSERT INTO backup_policies (server_id, destination_id, keep_last, keep_daily, keep_weekly, keep_monthly, ignore, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (server_id) DO UPDATE
SET destination_id = excluded.destination_id, keep_last = excluded.keep_last, keep_daily = excluded.keep_daily,
    keep_weekly = excluded.keep_weekly, keep_monthly = excluded.keep_monthly, ignore = excluded.ignore,
    version = backup_policies.version + 1, updated_at = excluded.updated_at
`

type UpsertBackupPolicyParams struct {
	ServerID      string
	DestinationID string
	KeepLast      int64
	KeepDaily     int64
	KeepWeekly    int64
	KeepMonthly   int64
	Ignore        string
	UpdatedAt     int64
}

func (q *Queries) UpsertBackupPolicy(ctx context.Context, arg UpsertBackupPolicyParams) error {
	_, err := q.db.ExecContext(ctx, upsertBackupPolicy,
		arg.ServerID,
		arg.DestinationID,
		arg.KeepLast,
		arg.KeepDaily,
		arg.KeepWeekly,
		arg.KeepMonthly,
		arg.Ignore,
		arg.UpdatedAt,
	)
	return err
}
