// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commands.sql

package store

import (
	"context"
	"database/sql"
)

const claimCommand = `-- name: ClaimCommand :execrows
INSERT INTO executed_commands (command_id, payload_hash, action, user_id, signed_by, status, received_at)
VALUES (?, ?, ?, ?, ?, 'running', ?)
ON CONFLICT (command_id) DO NOTHING
`

type ClaimCommandParams struct {
	CommandID   string
	PayloadHash []byte
	Action      string
	UserID      string
	SignedBy    []byte
	ReceivedAt  int64
}

func (q *Queries) ClaimCommand(ctx context.Context, arg ClaimCommandParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimCommand,
		arg.CommandID,
		arg.PayloadHash,
		arg.Action,
		arg.UserID,
		arg.SignedBy,
		arg.ReceivedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countOwnerKeys = `-- name: CountOwnerKeys :one
SELECT COUNT(*) FROM trusted_keys WHERE role = 'owner'
`

func (q *Queries) CountOwnerKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOwnerKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTrustedKey = `-- name: DeleteTrustedKey :execrows
DELETE FROM trusted_keys WHERE credential_id = ?
`

func (q *Queries) DeleteTrustedKey(ctx context.Context, credentialID []byte) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTrustedKey, credentialID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishCommand = `-- name: FinishCommand :exec
UPDATE executed_commands SET status = ?, result = ?, error = ?, finished_at = ? WHERE command_id = ?
`

type FinishCommandParams struct {
	Status     string
	Result     string
	Error      string
	FinishedAt sql.NullInt64
	CommandID  string
}

func (q *Queries) FinishCommand(ctx context.Context, arg FinishCommandParams) error {
	_, err := q.db.ExecContext(ctx, finishCommand,
		arg.Status,
		arg.Result,
		arg.Error,
		arg.FinishedAt,
		arg.CommandID,
	)
	return err
}

const getCommand = `-- name: GetCommand :one
SELECT command_id, payload_hash, "action", user_id, signed_by, status, result, error, received_at, finished_at FROM executed_commands WHERE command_id = ?
`

func (q *Queries) GetCommand(ctx context.Context, commandID string) (ExecutedCommand, error) {
	row := q.db.QueryRowContext(ctx, getCommand, commandID)
	var i ExecutedCommand
	err := row.Scan(
		&i.CommandID,
		&i.PayloadHash,
		&i.Action,
		&i.UserID,
		&i.SignedBy,
		&i.Status,
		&i.Result,
		&i.Error,
		&i.ReceivedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getTrustedKey = `-- name: GetTrustedKey :one
SELECT credential_id, user_id, public_key, role, server_id, actions, name, sign_count, expires_at, added_by, added_at FROM trusted_keys WHERE credential_id = ?
`

func (q *Queries) GetTrustedKey(ctx context.Context, credentialID []byte) (TrustedKey, error) {
	row := q.db.QueryRowContext(ctx, getTrustedKey, credentialID)
	var i TrustedKey
	err := row.Scan(
		&i.CredentialID,
		&i.UserID,
		&i.PublicKey,
		&i.Role,
		&i.ServerID,
		&i.Actions,
		&i.Name,
		&i.SignCount,
		&i.ExpiresAt,
		&i.AddedBy,
		&i.AddedAt,
	)
	return i, err
}

const insertTrustedKey = `-- name: InsertTrustedKey :exec
INSERT INTO trusted_keys (credential_id, user_id, public_key, role, server_id, actions, name, sign_count, expires_at, added_by, added_at)
VALUES (?, ?, ?, ?, ?, ?, ?, 0, ?, ?, ?)
`

type InsertTrustedKeyParams struct {
	CredentialID []byte
	UserID       string
	PublicKey    []byte
	Role         string
	ServerID     string
	Actions      string
	Name         string
	ExpiresAt    sql.NullInt64
	AddedBy      []byte
	AddedAt      int64
}

func (q *Queries) InsertTrustedKey(ctx context.Context, arg InsertTrustedKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertTrustedKey,
		arg.CredentialID,
		arg.UserID,
		arg.PublicKey,
		arg.Role,
		arg.ServerID,
		arg.Actions,
		arg.Name,
		arg.ExpiresAt,
		arg.AddedBy,
		arg.AddedAt,
	)
	return err
}

const interruptedCommands = `-- name: InterruptedCommands :execrows
UPDATE executed_commands SET status = 'failed', error = 'interrupted: Wings stopped while running it', finished_at = ?
WHERE status = 'running'
`

func (q *Queries) InterruptedCommands(ctx context.Context, finishedAt sql.NullInt64) (int64, error) {
	result, err := q.db.ExecContext(ctx, interruptedCommands, finishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listTrustedKeys = `-- name: ListTrustedKeys :many
SELECT credential_id, user_id, public_key, role, server_id, actions, name, sign_count, expires_at, added_by, added_at FROM trusted_keys ORDER BY added_at, credential_id
`

func (q *Queries) ListTrustedKeys(ctx context.Context) ([]TrustedKey, error) {
	rows, err := q.db.QueryContext(ctx, listTrustedKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrustedKey
	for rows.Next() {
		var i TrustedKey
		if err := rows.Scan(
			&i.CredentialID,
			&i.UserID,
			&i.PublicKey,
			&i.Role,
			&i.ServerID,
			&i.Actions,
			&i.Name,
			&i.SignCount,
			&i.ExpiresAt,
			&i.AddedBy,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneCommands = `-- name: PruneCommands :execrows
DELETE FROM executed_commands WHERE received_at < ? AND status != 'running'
`

func (q *Queries) PruneCommands(ctx context.Context, receivedAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneCommands, receivedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSignCount = `-- name: SetSignCount :exec
UPDATE trusted_keys SET sign_count = ? WHERE credential_id = ?
`

type SetSignCountParams struct {
	SignCount    int64
	CredentialID []byte
}

func (q *Queries) SetSignCount(ctx context.Context, arg SetSignCountParams) error {
	_, err := q.db.ExecContext(ctx, setSignCount, arg.SignCount, arg.CredentialID)
	return err
}
