// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package store

import (
	"context"
)

const appendEvent = `-- name: AppendEvent :one
INSERT INTO events (type, server_id, version, at, data) VALUES (?, ?, ?, ?, ?) RETURNING seq
`

type AppendEventParams struct {
	Type     string
	ServerID string
	Version  int64
	At       int64
	Data     string
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, appendEvent,
		arg.Type,
		arg.ServerID,
		arg.Version,
		arg.At,
		arg.Data,
	)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const eventsSince = `-- name: EventsSince :many
SELECT seq, type, server_id, version, at, data FROM events WHERE seq > ? ORDER BY seq LIMIT ?
`

type EventsSinceParams struct {
	Seq   int64
	Limit int64
}

func (q *Queries) EventsSince(ctx context.Context, arg EventsSinceParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, eventsSince, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.Seq,
			&i.Type,
			&i.ServerID,
			&i.Version,
			&i.At,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const firstEventSeq = `-- name: FirstEventSeq :one
SELECT CAST(COALESCE(MIN(seq), 0) AS INTEGER) FROM events
`

func (q *Queries) FirstEventSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, firstEventSeq)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const lastEventSeq = `-- name: LastEventSeq :one
SELECT CAST(COALESCE(MAX(seq), 0) AS INTEGER) FROM events
`

func (q *Queries) LastEventSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, lastEventSeq)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const pruneEvents = `-- name: PruneEvents :execrows
DELETE FROM events WHERE seq <= ?
`

func (q *Queries) PruneEvents(ctx context.Context, seq int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneEvents, seq)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
