// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package store

import (
	"context"
)

const createUpload = `-- name: CreateUpload :exec
INSERT INTO file_uploads (id, server_id, user_id, path, size, created_at, touched_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateUploadParams struct {
	ID        string
	ServerID  string
	UserID    string
	Path      string
	Size      int64
	CreatedAt int64
	TouchedAt int64
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) error {
	_, err := q.db.ExecContext(ctx, createUpload,
		arg.ID,
		arg.ServerID,
		arg.UserID,
		arg.Path,
		arg.Size,
		arg.CreatedAt,
		arg.TouchedAt,
	)
	return err
}

const deleteUpload = `-- name: DeleteUpload :exec
DELETE FROM file_uploads WHERE id = ?
`

func (q *Queries) DeleteUpload(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUpload, id)
	return err
}

const getUpload = `-- name: GetUpload :one
SELECT id, server_id, user_id, path, size, created_at, touched_at FROM file_uploads WHERE id = ?
`

func (q *Queries) GetUpload(ctx context.Context, id string) (FileUpload, error) {
	row := q.db.QueryRowContext(ctx, getUpload, id)
	var i FileUpload
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.UserID,
		&i.Path,
		&i.Size,
		&i.CreatedAt,
		&i.TouchedAt,
	)
	return i, err
}

const listIdleUploads = `-- name: ListIdleUploads :many
SELECT id, server_id, user_id, path, size, created_at, touched_at FROM file_uploads WHERE touched_at < ?
`

func (q *Queries) ListIdleUploads(ctx context.Context, touchedAt int64) ([]FileUpload, error) {
	rows, err := q.db.QueryContext(ctx, listIdleUploads, touchedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileUpload
	for rows.Next() {
		var i FileUpload
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.UserID,
			&i.Path,
			&i.Size,
			&i.CreatedAt,
			&i.TouchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchUpload = `-- name: TouchUpload :exec
UPDATE file_uploads SET touched_at = ? WHERE id = ?
`

type TouchUploadParams struct {
	TouchedAt int64
	ID        string
}

func (q *Queries) TouchUpload(ctx context.Context, arg TouchUploadParams) error {
	_, err := q.db.ExecContext(ctx, touchUpload, arg.TouchedAt, arg.ID)
	return err
}
