// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package store

import (
	"context"
	"database/sql"
)

const activeJobsForServer = `-- name: ActiveJobsForServer :one
SELECT COUNT(*) FROM jobs WHERE server_id = ? AND status IN ('queued', 'running')
`

func (q *Queries) ActiveJobsForServer(ctx context.Context, serverID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, activeJobsForServer, serverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const cancelQueuedJob = `-- name: CancelQueuedJob :execrows
UPDATE jobs SET status = 'cancelled', error = 'cancelled', finished_at = ? WHERE id = ? AND status = 'queued'
`

type CancelQueuedJobParams struct {
	FinishedAt sql.NullInt64
	ID         string
}

func (q *Queries) CancelQueuedJob(ctx context.Context, arg CancelQueuedJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelQueuedJob, arg.FinishedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishJob = `-- name: FinishJob :exec
UPDATE jobs SET status = ?, error = ?, result = ?, finished_at = ? WHERE id = ?
`

type FinishJobParams struct {
	Status     string
	Error      string
	Result     string
	FinishedAt sql.NullInt64
	ID         string
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) error {
	_, err := q.db.ExecContext(ctx, finishJob,
		arg.Status,
		arg.Error,
		arg.Result,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, server_id, type, payload, status, attempts, max_attempts, run_after, error, result, created_at, started_at, finished_at FROM jobs WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAfter,
		&i.Error,
		&i.Result,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :exec
INSERT INTO jobs (id, server_id, type, payload, status, max_attempts, run_after, created_at)
VALUES (?, ?, ?, ?, 'queued', ?, ?, ?)
`

type InsertJobParams struct {
	ID          string
	ServerID    string
	Type        string
	Payload     string
	MaxAttempts int64
	RunAfter    int64
	CreatedAt   int64
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) error {
	_, err := q.db.ExecContext(ctx, insertJob,
		arg.ID,
		arg.ServerID,
		arg.Type,
		arg.Payload,
		arg.MaxAttempts,
		arg.RunAfter,
		arg.CreatedAt,
	)
	return err
}

const listJobs = `-- name: ListJobs :many
SELECT id, server_id, type, payload, status, attempts, max_attempts, run_after, error, result, created_at, started_at, finished_at FROM jobs WHERE (?1 = '' OR server_id = ?1)
ORDER BY created_at DESC LIMIT ?2
`

type ListJobsParams struct {
	ServerID interface{}
	Lim      int64
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs, arg.ServerID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Type,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.RunAfter,
			&i.Error,
			&i.Result,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobRunning = `-- name: MarkJobRunning :execrows
UPDATE jobs SET status = 'running', attempts = attempts + 1, started_at = ?
WHERE id = ? AND status = 'queued'
`

type MarkJobRunningParams struct {
	StartedAt sql.NullInt64
	ID        string
}

func (q *Queries) MarkJobRunning(ctx context.Context, arg MarkJobRunningParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markJobRunning, arg.StartedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const nextRunAfter = `-- name: NextRunAfter :one
SELECT CAST(COALESCE(MIN(run_after), 0) AS INTEGER) FROM jobs WHERE status = 'queued'
`

func (q *Queries) NextRunAfter(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextRunAfter)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const pruneJobs = `-- name: PruneJobs :many
DELETE FROM jobs WHERE status IN ('succeeded', 'failed', 'cancelled') AND finished_at < ? RETURNING id
`

func (q *Queries) PruneJobs(ctx context.Context, finishedAt sql.NullInt64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, pruneJobs, finishedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueJob = `-- name: RequeueJob :exec
UPDATE jobs SET status = 'queued', error = ?, run_after = ? WHERE id = ?
`

type RequeueJobParams struct {
	Error    string
	RunAfter int64
	ID       string
}

func (q *Queries) RequeueJob(ctx context.Context, arg RequeueJobParams) error {
	_, err := q.db.ExecContext(ctx, requeueJob, arg.Error, arg.RunAfter, arg.ID)
	return err
}

const runnableJobs = `-- name: RunnableJobs :many
SELECT id, server_id, type, payload, status, attempts, max_attempts, run_after, error, result, created_at, started_at, finished_at FROM jobs WHERE status = 'queued' AND run_after <= ? ORDER BY run_after, created_at LIMIT 100
`

func (q *Queries) RunnableJobs(ctx context.Context, runAfter int64) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, runnableJobs, runAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Type,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.RunAfter,
			&i.Error,
			&i.Result,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runningJobs = `-- name: RunningJobs :many
SELECT id, server_id, type, payload, status, attempts, max_attempts, run_after, error, result, created_at, started_at, finished_at FROM jobs WHERE status = 'running'
`

func (q *Queries) RunningJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, runningJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Type,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.RunAfter,
			&i.Error,
			&i.Result,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
