// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kv.sql

package store

import (
	"context"
)

const getKV = `-- name: GetKV :one
SELECT value FROM kv WHERE key = ?
`

func (q *Queries) GetKV(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getKV, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const setKV = `-- name: SetKV :exec
INSERT INTO kv (key, value, updated_at)
VALUES (?, ?, unixepoch())
ON CONFLICT (key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
`

type SetKVParams struct {
	Key   string
	Value []byte
}

func (q *Queries) SetKV(ctx context.Context, arg SetKVParams) error {
	_, err := q.db.ExecContext(ctx, setKV, arg.Key, arg.Value)
	return err
}
