// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package store

import (
	"context"
	"database/sql"
)

const deleteMetricsBefore = `-- name: DeleteMetricsBefore :execrows
DELETE FROM metrics WHERE resolution = ? AND at < ?
`

type DeleteMetricsBeforeParams struct {
	Resolution int64
	At         int64
}

func (q *Queries) DeleteMetricsBefore(ctx context.Context, arg DeleteMetricsBeforeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMetricsBefore, arg.Resolution, arg.At)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listMetrics = `-- name: ListMetrics :many
SELECT server_id, resolution, at, samples, cpu_avg, cpu_max, memory_avg, memory_max, rx_bytes, tx_bytes, disk_bytes, players_avg, players_max FROM metrics WHERE server_id = ? AND resolution = ? AND at >= ? ORDER BY at
`

type ListMetricsParams struct {
	ServerID   string
	Resolution int64
	At         int64
}

func (q *Queries) ListMetrics(ctx context.Context, arg ListMetricsParams) ([]Metric, error) {
	rows, err := q.db.QueryContext(ctx, listMetrics, arg.ServerID, arg.Resolution, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metric
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.ServerID,
			&i.Resolution,
			&i.At,
			&i.Samples,
			&i.CpuAvg,
			&i.CpuMax,
			&i.MemoryAvg,
			&i.MemoryMax,
			&i.RxBytes,
			&i.TxBytes,
			&i.DiskBytes,
			&i.PlayersAvg,
			&i.PlayersMax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const metricsBefore = `-- name: MetricsBefore :many
SELECT server_id, resolution, at, samples, cpu_avg, cpu_max, memory_avg, memory_max, rx_bytes, tx_bytes, disk_bytes, players_avg, players_max FROM metrics WHERE resolution = 60 AND at < ? ORDER BY server_id, at
`

// Minute rows old enough to be rolled up.
func (q *Queries) MetricsBefore(ctx context.Context, at int64) ([]Metric, error) {
	rows, err := q.db.QueryContext(ctx, metricsBefore, at)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metric
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.ServerID,
			&i.Resolution,
			&i.At,
			&i.Samples,
			&i.CpuAvg,
			&i.CpuMax,
			&i.MemoryAvg,
			&i.MemoryMax,
			&i.RxBytes,
			&i.TxBytes,
			&i.DiskBytes,
			&i.PlayersAvg,
			&i.PlayersMax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMetric = `-- name: UpsertMetric :exec
INSERT INTO metrics (server_id, resolution, at, samples, cpu_avg, cpu_max, memory_avg, memory_max, rx_bytes, tx_bytes, disk_bytes, players_avg, players_max)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (server_id, resolution, at) DO UPDATE SET
    samples = excluded.samples, cpu_avg = excluded.cpu_avg, cpu_max = excluded.cpu_max,
    memory_avg = excluded.memory_avg, memory_max = excluded.memory_max, rx_bytes = excluded.rx_bytes,
    tx_bytes = excluded.tx_bytes, disk_bytes = excluded.disk_bytes, players_avg = excluded.players_avg,
    players_max = excluded.players_max
`

type UpsertMetricParams struct {
	ServerID   string
	Resolution int64
	At         int64
	Samples    int64
	CpuAvg     float64
	CpuMax     float64
	MemoryAvg  int64
	MemoryMax  int64
	RxBytes    int64
	TxBytes    int64
	DiskBytes  int64
	PlayersAvg sql.NullFloat64
	PlayersMax sql.NullInt64
}

func (q *Queries) UpsertMetric(ctx context.Context, arg UpsertMetricParams) error {
	_, err := q.db.ExecContext(ctx, upsertMetric,
		arg.ServerID,
		arg.Resolution,
		arg.At,
		arg.Samples,
		arg.CpuAvg,
		arg.CpuMax,
		arg.MemoryAvg,
		arg.MemoryMax,
		arg.RxBytes,
		arg.TxBytes,
		arg.DiskBytes,
		arg.PlayersAvg,
		arg.PlayersMax,
	)
	return err
}
