// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type Allocation struct {
	ServerID  string
	Ip        string
	Port      int64
	IsPrimary int64
}

type Backup struct {
	ID            string
	ServerID      string
	DestinationID string
	Kind          string
	Status        string
	Locked        int64
	SnapshotID    string
	Size          int64
	Files         int64
	Uploaded      int64
	Warning       string
	Error         string
	JobID         string
	CreatedBy     string
	CreatedAt     int64
	FinishedAt    sql.NullInt64
	ExpiresAt     sql.NullInt64
}

type BackupDestination struct {
	ID        string
	Name      string
	Type      string
	Config    string
	Version   int64
	CreatedAt int64
	UpdatedAt int64
}

type BackupPolicy struct {
	ServerID      string
	DestinationID string
	KeepLast      int64
	KeepDaily     int64
	KeepWeekly    int64
	KeepMonthly   int64
	Ignore        string
	Version       int64
	UpdatedAt     int64
}

type Event struct {
	Seq      int64
	Type     string
	ServerID string
	Version  int64
	At       int64
	Data     string
}

type ExecutedCommand struct {
	CommandID   string
	PayloadHash []byte
	Action      string
	UserID      string
	SignedBy    []byte
	Status      string
	Result      string
	Error       string
	ReceivedAt  int64
	FinishedAt  sql.NullInt64
}

type FileUpload struct {
	ID        string
	ServerID  string
	UserID    string
	Path      string
	Size      int64
	CreatedAt int64
	TouchedAt int64
}

type Job struct {
	ID          string
	ServerID    string
	Type        string
	Payload     string
	Status      string
	Attempts    int64
	MaxAttempts int64
	RunAfter    int64
	Error       string
	Result      string
	CreatedAt   int64
	StartedAt   sql.NullInt64
	FinishedAt  sql.NullInt64
	Checkpoint  string
}

type Kv struct {
	Key       string
	Value     []byte
	UpdatedAt int64
}

type Schedule struct {
	ID             string
	ServerID       string
	Name           string
	Cron           string
	Timezone       string
	Enabled        int64
	OnlyWhenOnline int64
	JitterS        int64
	Missed         string
	Steps          string
	NextRunAt      sql.NullInt64
	LastRunAt      sql.NullInt64
	Version        int64
	CreatedAt      int64
	UpdatedAt      int64
}

type Server struct {
	ID           string
	Name         string
	Egg          []byte
	EggSource    string
	EggHash      string
	Image        string
	Startup      string
	Variables    string
	Limits       string
	Settings     string
	HostNetwork  int64
	DesiredState string
	InstallState string
	InstallError string
	LastState    string
	Version      int64
	CreatedAt    int64
	UpdatedAt    int64
	QuotaProject sql.NullInt64
}

type SftpKeyCache struct {
	Username    string
	ServerID    string
	Fingerprint string
	PublicKey   []byte
	UserID      string
	Permissions string
	ConfirmedAt int64
}

type TrustedKey struct {
	CredentialID []byte
	UserID       string
	PublicKey    []byte
	Role         string
	ServerID     string
	Actions      string
	Name         string
	SignCount    int64
	ExpiresAt    sql.NullInt64
	AddedBy      []byte
	AddedAt      int64
}
