// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package store

import (
	"context"
	"database/sql"
)

const activeScheduleRuns = `-- name: ActiveScheduleRuns :many
SELECT id FROM jobs
WHERE type = 'schedule.run' AND status IN ('queued', 'running') AND json_extract(payload, '$.schedule_id') = ?
`

func (q *Queries) ActiveScheduleRuns(ctx context.Context, payload string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, activeScheduleRuns, payload)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const advanceSchedule = `-- name: AdvanceSchedule :execrows
UPDATE schedules SET next_run_at = ?1, last_run_at = COALESCE(?2, last_run_at)
WHERE id = ?3 AND version = ?4
`

type AdvanceScheduleParams struct {
	NextRunAt sql.NullInt64
	LastRunAt sql.NullInt64
	ID        string
	Version   int64
}

// Moves a schedule past a run, unless it was changed meanwhile.
func (q *Queries) AdvanceSchedule(ctx context.Context, arg AdvanceScheduleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceSchedule,
		arg.NextRunAt,
		arg.LastRunAt,
		arg.ID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countServerSchedules = `-- name: CountServerSchedules :one
SELECT COUNT(*) FROM schedules WHERE server_id = ?
`

func (q *Queries) CountServerSchedules(ctx context.Context, serverID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countServerSchedules, serverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules WHERE id = ?
`

func (q *Queries) DeleteSchedule(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSchedule, id)
	return err
}

const dueSchedules = `-- name: DueSchedules :many
SELECT id, server_id, name, cron, timezone, enabled, only_when_online, jitter_s, missed, steps, next_run_at, last_run_at, version, created_at, updated_at FROM schedules WHERE next_run_at IS NOT NULL AND next_run_at <= ? ORDER BY next_run_at LIMIT 100
`

func (q *Queries) DueSchedules(ctx context.Context, nextRunAt sql.NullInt64) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, dueSchedules, nextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Name,
			&i.Cron,
			&i.Timezone,
			&i.Enabled,
			&i.OnlyWhenOnline,
			&i.JitterS,
			&i.Missed,
			&i.Steps,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, server_id, name, cron, timezone, enabled, only_when_online, jitter_s, missed, steps, next_run_at, last_run_at, version, created_at, updated_at FROM schedules WHERE id = ?
`

func (q *Queries) GetSchedule(ctx context.Context, id string) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, getSchedule, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.Cron,
		&i.Timezone,
		&i.Enabled,
		&i.OnlyWhenOnline,
		&i.JitterS,
		&i.Missed,
		&i.Steps,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSchedule = `-- name: InsertSchedule :exec
INSERT INTO schedules (id, server_id, name, cron, timezone, enabled, only_when_online, jitter_s, missed, steps,
                       next_run_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertScheduleParams struct {
	ID             string
	ServerID       string
	Name           string
	Cron           string
	Timezone       string
	Enabled        int64
	OnlyWhenOnline int64
	JitterS        int64
	Missed         string
	Steps          string
	NextRunAt      sql.NullInt64
	CreatedAt      int64
	UpdatedAt      int64
}

func (q *Queries) InsertSchedule(ctx context.Context, arg InsertScheduleParams) error {
	_, err := q.db.ExecContext(ctx, insertSchedule,
		arg.ID,
		arg.ServerID,
		arg.Name,
		arg.Cron,
		arg.Timezone,
		arg.Enabled,
		arg.OnlyWhenOnline,
		arg.JitterS,
		arg.Missed,
		arg.Steps,
		arg.NextRunAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, server_id, name, cron, timezone, enabled, only_when_online, jitter_s, missed, steps, next_run_at, last_run_at, version, created_at, updated_at FROM schedules WHERE (?1 = '' OR server_id = ?1)
ORDER BY created_at, id
`

func (q *Queries) ListSchedules(ctx context.Context, serverID interface{}) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedules, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Name,
			&i.Cron,
			&i.Timezone,
			&i.Enabled,
			&i.OnlyWhenOnline,
			&i.JitterS,
			&i.Missed,
			&i.Steps,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextScheduleRun = `-- name: NextScheduleRun :one
SELECT CAST(COALESCE(MIN(next_run_at), 0) AS INTEGER) FROM schedules WHERE next_run_at IS NOT NULL
`

func (q *Queries) NextScheduleRun(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextScheduleRun)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateSchedule = `-- name: UpdateSchedule :exec
UPDATE schedules
SET name = ?, cron = ?, timezone = ?, enabled = ?, only_when_online = ?, jitter_s = ?, missed = ?, steps = ?,
    next_run_at = ?, version = version + 1, updated_at = ?
WHERE id = ?
`

type UpdateScheduleParams struct {
	Name           string
	Cron           string
	Timezone       string
	Enabled        int64
	OnlyWhenOnline int64
	JitterS        int64
	Missed         string
	Steps          string
	NextRunAt      sql.NullInt64
	UpdatedAt      int64
	ID             string
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) error {
	_, err := q.db.ExecContext(ctx, updateSchedule,
		arg.Name,
		arg.Cron,
		arg.Timezone,
		arg.Enabled,
		arg.OnlyWhenOnline,
		arg.JitterS,
		arg.Missed,
		arg.Steps,
		arg.NextRunAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
