// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: servers.sql

package store

import (
	"context"
)

const deleteServer = `-- name: DeleteServer :exec
DELETE FROM servers WHERE id = ?
`

func (q *Queries) DeleteServer(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteServer, id)
	return err
}

const deleteServerAllocations = `-- name: DeleteServerAllocations :exec
DELETE FROM allocations WHERE server_id = ?
`

func (q *Queries) DeleteServerAllocations(ctx context.Context, serverID string) error {
	_, err := q.db.ExecContext(ctx, deleteServerAllocations, serverID)
	return err
}

const getServer = `-- name: GetServer :one
SELECT id, name, egg, egg_source, egg_hash, image, startup, variables, limits, settings, host_network, desired_state, install_state, install_error, last_state, version, created_at, updated_at FROM servers WHERE id = ?
`

func (q *Queries) GetServer(ctx context.Context, id string) (Server, error) {
	row := q.db.QueryRowContext(ctx, getServer, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Egg,
		&i.EggSource,
		&i.EggHash,
		&i.Image,
		&i.Startup,
		&i.Variables,
		&i.Limits,
		&i.Settings,
		&i.HostNetwork,
		&i.DesiredState,
		&i.InstallState,
		&i.InstallError,
		&i.LastState,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAllocation = `-- name: InsertAllocation :exec
INSERT INTO allocations (server_id, ip, port, is_primary) VALUES (?, ?, ?, ?)
`

type InsertAllocationParams struct {
	ServerID  string
	Ip        string
	Port      int64
	IsPrimary int64
}

func (q *Queries) InsertAllocation(ctx context.Context, arg InsertAllocationParams) error {
	_, err := q.db.ExecContext(ctx, insertAllocation,
		arg.ServerID,
		arg.Ip,
		arg.Port,
		arg.IsPrimary,
	)
	return err
}

const insertServer = `-- name: InsertServer :exec
INSERT INTO servers (id, name, egg, egg_source, egg_hash, image, startup, variables, limits, settings,
                     host_network, desired_state, install_state, version, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, unixepoch(), unixepoch())
`

type InsertServerParams struct {
	ID           string
	Name         string
	Egg          []byte
	EggSource    string
	EggHash      string
	Image        string
	Startup      string
	Variables    string
	Limits       string
	Settings     string
	HostNetwork  int64
	DesiredState string
	InstallState string
}

func (q *Queries) InsertServer(ctx context.Context, arg InsertServerParams) error {
	_, err := q.db.ExecContext(ctx, insertServer,
		arg.ID,
		arg.Name,
		arg.Egg,
		arg.EggSource,
		arg.EggHash,
		arg.Image,
		arg.Startup,
		arg.Variables,
		arg.Limits,
		arg.Settings,
		arg.HostNetwork,
		arg.DesiredState,
		arg.InstallState,
	)
	return err
}

const listAllocations = `-- name: ListAllocations :many
SELECT server_id, ip, port, is_primary FROM allocations ORDER BY server_id, is_primary DESC, ip, port
`

func (q *Queries) ListAllocations(ctx context.Context) ([]Allocation, error) {
	rows, err := q.db.QueryContext(ctx, listAllocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Allocation
	for rows.Next() {
		var i Allocation
		if err := rows.Scan(
			&i.ServerID,
			&i.Ip,
			&i.Port,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServerAllocations = `-- name: ListServerAllocations :many
SELECT server_id, ip, port, is_primary FROM allocations WHERE server_id = ? ORDER BY is_primary DESC, ip, port
`

func (q *Queries) ListServerAllocations(ctx context.Context, serverID string) ([]Allocation, error) {
	rows, err := q.db.QueryContext(ctx, listServerAllocations, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Allocation
	for rows.Next() {
		var i Allocation
		if err := rows.Scan(
			&i.ServerID,
			&i.Ip,
			&i.Port,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServers = `-- name: ListServers :many
SELECT id, name, egg, egg_source, egg_hash, image, startup, variables, limits, settings, host_network, desired_state, install_state, install_error, last_state, version, created_at, updated_at FROM servers ORDER BY created_at, id
`

func (q *Queries) ListServers(ctx context.Context) ([]Server, error) {
	rows, err := q.db.QueryContext(ctx, listServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Server
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Egg,
			&i.EggSource,
			&i.EggHash,
			&i.Image,
			&i.Startup,
			&i.Variables,
			&i.Limits,
			&i.Settings,
			&i.HostNetwork,
			&i.DesiredState,
			&i.InstallState,
			&i.InstallError,
			&i.LastState,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceEgg = `-- name: ReplaceEgg :exec
UPDATE servers
SET egg = ?, egg_source = ?, egg_hash = ?, image = ?, startup = ?, version = version + 1, updated_at = unixepoch()
WHERE id = ?
`

type ReplaceEggParams struct {
	Egg       []byte
	EggSource string
	EggHash   string
	Image     string
	Startup   string
	ID        string
}

func (q *Queries) ReplaceEgg(ctx context.Context, arg ReplaceEggParams) error {
	_, err := q.db.ExecContext(ctx, replaceEgg,
		arg.Egg,
		arg.EggSource,
		arg.EggHash,
		arg.Image,
		arg.Startup,
		arg.ID,
	)
	return err
}

const setDesiredState = `-- name: SetDesiredState :exec
UPDATE servers SET desired_state = ?, updated_at = unixepoch() WHERE id = ?
`

type SetDesiredStateParams struct {
	DesiredState string
	ID           string
}

func (q *Queries) SetDesiredState(ctx context.Context, arg SetDesiredStateParams) error {
	_, err := q.db.ExecContext(ctx, setDesiredState, arg.DesiredState, arg.ID)
	return err
}

const setInstallState = `-- name: SetInstallState :exec
UPDATE servers SET install_state = ?, install_error = ?, updated_at = unixepoch() WHERE id = ?
`

type SetInstallStateParams struct {
	InstallState string
	InstallError string
	ID           string
}

func (q *Queries) SetInstallState(ctx context.Context, arg SetInstallStateParams) error {
	_, err := q.db.ExecContext(ctx, setInstallState, arg.InstallState, arg.InstallError, arg.ID)
	return err
}

const setLastState = `-- name: SetLastState :exec
UPDATE servers SET last_state = ? WHERE id = ?
`

type SetLastStateParams struct {
	LastState string
	ID        string
}

func (q *Queries) SetLastState(ctx context.Context, arg SetLastStateParams) error {
	_, err := q.db.ExecContext(ctx, setLastState, arg.LastState, arg.ID)
	return err
}

const updateServerConfig = `-- name: UpdateServerConfig :exec
UPDATE servers
SET name = ?, image = ?, startup = ?, variables = ?, limits = ?, settings = ?, host_network = ?,
    version = version + 1, updated_at = unixepoch()
WHERE id = ?
`

type UpdateServerConfigParams struct {
	Name        string
	Image       string
	Startup     string
	Variables   string
	Limits      string
	Settings    string
	HostNetwork int64
	ID          string
}

func (q *Queries) UpdateServerConfig(ctx context.Context, arg UpdateServerConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateServerConfig,
		arg.Name,
		arg.Image,
		arg.Startup,
		arg.Variables,
		arg.Limits,
		arg.Settings,
		arg.HostNetwork,
		arg.ID,
	)
	return err
}
