// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sftp.sql

package store

import (
	"context"
)

const deleteSFTPKey = `-- name: DeleteSFTPKey :exec
DELETE FROM sftp_key_cache WHERE username = ? AND server_id = ? AND fingerprint = ?
`

type DeleteSFTPKeyParams struct {
	Username    string
	ServerID    string
	Fingerprint string
}

func (q *Queries) DeleteSFTPKey(ctx context.Context, arg DeleteSFTPKeyParams) error {
	_, err := q.db.ExecContext(ctx, deleteSFTPKey, arg.Username, arg.ServerID, arg.Fingerprint)
	return err
}

const getSFTPKey = `-- name: GetSFTPKey :one
SELECT username, server_id, fingerprint, public_key, user_id, permissions, confirmed_at FROM sftp_key_cache WHERE username = ? AND server_id = ? AND fingerprint = ?
`

type GetSFTPKeyParams struct {
	Username    string
	ServerID    string
	Fingerprint string
}

func (q *Queries) GetSFTPKey(ctx context.Context, arg GetSFTPKeyParams) (SftpKeyCache, error) {
	row := q.db.QueryRowContext(ctx, getSFTPKey, arg.Username, arg.ServerID, arg.Fingerprint)
	var i SftpKeyCache
	err := row.Scan(
		&i.Username,
		&i.ServerID,
		&i.Fingerprint,
		&i.PublicKey,
		&i.UserID,
		&i.Permissions,
		&i.ConfirmedAt,
	)
	return i, err
}

const pruneSFTPKeys = `-- name: PruneSFTPKeys :execrows
DELETE FROM sftp_key_cache WHERE confirmed_at < ?
`

func (q *Queries) PruneSFTPKeys(ctx context.Context, confirmedAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneSFTPKeys, confirmedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertSFTPKey = `-- name: UpsertSFTPKey :exec
INSERT INTO sftp_key_cache (username, server_id, fingerprint, public_key, user_id, permissions, confirmed_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (username, server_id, fingerprint) DO UPDATE SET
    public_key = excluded.public_key,
    user_id = excluded.user_id,
    permissions = excluded.permissions,
    confirmed_at = excluded.confirmed_at
`

type UpsertSFTPKeyParams struct {
	Username    string
	ServerID    string
	Fingerprint string
	PublicKey   []byte
	UserID      string
	Permissions string
	ConfirmedAt int64
}

func (q *Queries) UpsertSFTPKey(ctx context.Context, arg UpsertSFTPKeyParams) error {
	_, err := q.db.ExecContext(ctx, upsertSFTPKey,
		arg.Username,
		arg.ServerID,
		arg.Fingerprint,
		arg.PublicKey,
		arg.UserID,
		arg.Permissions,
		arg.ConfirmedAt,
	)
	return err
}
