/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OrgsOrgIdRouteImport } from './routes/orgs.$orgId'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsActivityRouteImport } from './routes/settings.activity'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SigninIndexRouteImport } from './routes/signin.index'
import { Route as SigninLinkRouteImport } from './routes/signin.link'
import { Route as SigninSecondFactorRouteImport } from './routes/signin.second-factor'
import { Route as OrgsOrgIdIndexRouteImport } from './routes/orgs.$orgId.index'
import { Route as OrgsOrgIdEggsRouteImport } from './routes/orgs.$orgId.eggs'
import { Route as OrgsOrgIdSettingsRouteImport } from './routes/orgs.$orgId.settings'
import { Route as OrgsOrgIdNodesIndexRouteImport } from './routes/orgs.$orgId.nodes.index'
import { Route as OrgsOrgIdNodesNodeIdRouteImport } from './routes/orgs.$orgId.nodes.$nodeId'
import { Route as OrgsOrgIdNodesNewRouteImport } from './routes/orgs.$orgId.nodes.new'
import { Route as OrgsOrgIdServersIndexRouteImport } from './routes/orgs.$orgId.servers.index'
import { Route as OrgsOrgIdServersNewRouteImport } from './routes/orgs.$orgId.servers.new'
import { Route as OrgsOrgIdSettingsIndexRouteImport } from './routes/orgs.$orgId.settings.index'
import { Route as OrgsOrgIdSettingsActivityRouteImport } from './routes/orgs.$orgId.settings.activity'
import { Route as OrgsOrgIdSettingsBillingRouteImport } from './routes/orgs.$orgId.settings.billing'
import { Route as OrgsOrgIdSettingsMembersRouteImport } from './routes/orgs.$orgId.settings.members'
import { Route as OrgsOrgIdNodesNodeIdIndexRouteImport } from './routes/orgs.$orgId.nodes.$nodeId.index'
import { Route as OrgsOrgIdNodesNodeIdHealthRouteImport } from './routes/orgs.$orgId.nodes.$nodeId.health'
import { Route as OrgsOrgIdNodesNodeIdSettingsRouteImport } from './routes/orgs.$orgId.nodes.$nodeId.settings'
import { Route as OrgsOrgIdServersNodeIdServerIdRouteImport } from './routes/orgs.$orgId.servers.$nodeId.$serverId'
import { Route as OrgsOrgIdServersNodeIdServerIdIndexRouteImport } from './routes/orgs.$orgId.servers.$nodeId.$serverId.index'
import { Route as OrgsOrgIdServersNodeIdServerIdAccessRouteImport } from './routes/orgs.$orgId.servers.$nodeId.$serverId.access'
import { Route as OrgsOrgIdServersNodeIdServerIdActivityRouteImport } from './routes/orgs.$orgId.servers.$nodeId.$serverId.activity'
import { Route as OrgsOrgIdServersNodeIdServerIdBackupsRouteImport } from './routes/orgs.$orgId.servers.$nodeId.$serverId.backups'
import { Route as OrgsOrgIdServersNodeIdServerIdDatabasesRouteImport } from './routes/orgs.$orgId.servers.$nodeId.$serverId.databases'
import { Route as OrgsOrgIdServersNodeIdServerIdFilesRouteImport } from './routes/orgs.$orgId.servers.$nodeId.$serverId.files'
import { Route as OrgsOrgIdServersNodeIdServerIdNetworkRouteImport } from './routes/orgs.$orgId.servers.$nodeId.$serverId.network'
import { Route as OrgsOrgIdServersNodeIdServerIdSchedulesRouteImport } from './routes/orgs.$orgId.servers.$nodeId.$serverId.schedules'
import { Route as OrgsOrgIdServersNodeIdServerIdSettingsRouteImport } from './routes/orgs.$orgId.servers.$nodeId.$serverId.settings'
import { Route as OrgsOrgIdServersNodeIdServerIdStartupRouteImport } from './routes/orgs.$orgId.servers.$nodeId.$serverId.startup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsOrgIdRoute = OrgsOrgIdRouteImport.update({
  id: '/orgs/$orgId',
  path: '/orgs/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsActivityRoute = SettingsActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SigninIndexRoute = SigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninLinkRoute = SigninLinkRouteImport.update({
  id: '/signin/link',
  path: '/signin/link',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninSecondFactorRoute = SigninSecondFactorRouteImport.update({
  id: '/signin/second-factor',
  path: '/signin/second-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsOrgIdIndexRoute = OrgsOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgsOrgIdRoute,
} as any)
const OrgsOrgIdEggsRoute = OrgsOrgIdEggsRouteImport.update({
  id: '/eggs',
  path: '/eggs',
  getParentRoute: () => OrgsOrgIdRoute,
} as any)
const OrgsOrgIdSettingsRoute = OrgsOrgIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgsOrgIdRoute,
} as any)
const OrgsOrgIdNodesIndexRoute = OrgsOrgIdNodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => OrgsOrgIdRoute,
} as any)
const OrgsOrgIdNodesNodeIdRoute = OrgsOrgIdNodesNodeIdRouteImport.update({
  id: '/nodes/$nodeId',
  path: '/nodes/$nodeId',
  getParentRoute: () => OrgsOrgIdRoute,
} as any)
const OrgsOrgIdNodesNewRoute = OrgsOrgIdNodesNewRouteImport.update({
  id: '/nodes/new',
  path: '/nodes/new',
  getParentRoute: () => OrgsOrgIdRoute,
} as any)
const OrgsOrgIdServersIndexRoute = OrgsOrgIdServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => OrgsOrgIdRoute,
} as any)
const OrgsOrgIdServersNewRoute = OrgsOrgIdServersNewRouteImport.update({
  id: '/servers/new',
  path: '/servers/new',
  getParentRoute: () => OrgsOrgIdRoute,
} as any)
const OrgsOrgIdSettingsIndexRoute = OrgsOrgIdSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgsOrgIdSettingsRoute,
} as any)
const OrgsOrgIdSettingsActivityRoute =
  OrgsOrgIdSettingsActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => OrgsOrgIdSettingsRoute,
  } as any)
const OrgsOrgIdSettingsBillingRoute =
  OrgsOrgIdSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => OrgsOrgIdSettingsRoute,
  } as any)
const OrgsOrgIdSettingsMembersRoute =
  OrgsOrgIdSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => OrgsOrgIdSettingsRoute,
  } as any)
const OrgsOrgIdNodesNodeIdIndexRoute =
  OrgsOrgIdNodesNodeIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgsOrgIdNodesNodeIdRoute,
  } as any)
const OrgsOrgIdNodesNodeIdHealthRoute =
  OrgsOrgIdNodesNodeIdHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => OrgsOrgIdNodesNodeIdRoute,
  } as any)
const OrgsOrgIdNodesNodeIdSettingsRoute =
  OrgsOrgIdNodesNodeIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OrgsOrgIdNodesNodeIdRoute,
  } as any)
const OrgsOrgIdServersNodeIdServerIdRoute =
  OrgsOrgIdServersNodeIdServerIdRouteImport.update({
    id: '/servers/$nodeId/$serverId',
    path: '/servers/$nodeId/$serverId',
    getParentRoute: () => OrgsOrgIdRoute,
  } as any)
const OrgsOrgIdServersNodeIdServerIdIndexRoute =
  OrgsOrgIdServersNodeIdServerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgsOrgIdServersNodeIdServerIdRoute,
  } as any)
const OrgsOrgIdServersNodeIdServerIdAccessRoute =
  OrgsOrgIdServersNodeIdServerIdAccessRouteImport.update({
    id: '/access',
    path: '/access',
    getParentRoute: () => OrgsOrgIdServersNodeIdServerIdRoute,
  } as any)
const OrgsOrgIdServersNodeIdServerIdActivityRoute =
  OrgsOrgIdServersNodeIdServerIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => OrgsOrgIdServersNodeIdServerIdRoute,
  } as any)
const OrgsOrgIdServersNodeIdServerIdBackupsRoute =
  OrgsOrgIdServersNodeIdServerIdBackupsRouteImport.update({
    id: '/backups',
    path: '/backups',
    getParentRoute: () => OrgsOrgIdServersNodeIdServerIdRoute,
  } as any)
const OrgsOrgIdServersNodeIdServerIdDatabasesRoute =
  OrgsOrgIdServersNodeIdServerIdDatabasesRouteImport.update({
    id: '/databases',
    path: '/databases',
    getParentRoute: () => OrgsOrgIdServersNodeIdServerIdRoute,
  } as any)
const OrgsOrgIdServersNodeIdServerIdFilesRoute =
  OrgsOrgIdServersNodeIdServerIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => OrgsOrgIdServersNodeIdServerIdRoute,
  } as any)
const OrgsOrgIdServersNodeIdServerIdNetworkRoute =
  OrgsOrgIdServersNodeIdServerIdNetworkRouteImport.update({
    id: '/network',
    path: '/network',
    getParentRoute: () => OrgsOrgIdServersNodeIdServerIdRoute,
  } as any)
const OrgsOrgIdServersNodeIdServerIdSchedulesRoute =
  OrgsOrgIdServersNodeIdServerIdSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => OrgsOrgIdServersNodeIdServerIdRoute,
  } as any)
const OrgsOrgIdServersNodeIdServerIdSettingsRoute =
  OrgsOrgIdServersNodeIdServerIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OrgsOrgIdServersNodeIdServerIdRoute,
  } as any)
const OrgsOrgIdServersNodeIdServerIdStartupRoute =
  OrgsOrgIdServersNodeIdServerIdStartupRouteImport.update({
    id: '/startup',
    path: '/startup',
    getParentRoute: () => OrgsOrgIdServersNodeIdServerIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/settings': typeof SettingsRouteWithChildren
  '/orgs/$orgId': typeof OrgsOrgIdRouteWithChildren
  '/settings/activity': typeof SettingsActivityRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/signin/link': typeof SigninLinkRoute
  '/signin/second-factor': typeof SigninSecondFactorRoute
  '/settings/': typeof SettingsIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/orgs/$orgId/eggs': typeof OrgsOrgIdEggsRoute
  '/orgs/$orgId/settings': typeof OrgsOrgIdSettingsRouteWithChildren
  '/orgs/$orgId/': typeof OrgsOrgIdIndexRoute
  '/orgs/$orgId/nodes/$nodeId': typeof OrgsOrgIdNodesNodeIdRouteWithChildren
  '/orgs/$orgId/nodes/new': typeof OrgsOrgIdNodesNewRoute
  '/orgs/$orgId/servers/new': typeof OrgsOrgIdServersNewRoute
  '/orgs/$orgId/settings/activity': typeof OrgsOrgIdSettingsActivityRoute
  '/orgs/$orgId/settings/billing': typeof OrgsOrgIdSettingsBillingRoute
  '/orgs/$orgId/settings/members': typeof OrgsOrgIdSettingsMembersRoute
  '/orgs/$orgId/nodes/': typeof OrgsOrgIdNodesIndexRoute
  '/orgs/$orgId/servers/': typeof OrgsOrgIdServersIndexRoute
  '/orgs/$orgId/settings/': typeof OrgsOrgIdSettingsIndexRoute
  '/orgs/$orgId/nodes/$nodeId/health': typeof OrgsOrgIdNodesNodeIdHealthRoute
  '/orgs/$orgId/nodes/$nodeId/settings': typeof OrgsOrgIdNodesNodeIdSettingsRoute
  '/orgs/$orgId/servers/$nodeId/$serverId': typeof OrgsOrgIdServersNodeIdServerIdRouteWithChildren
  '/orgs/$orgId/nodes/$nodeId/': typeof OrgsOrgIdNodesNodeIdIndexRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/access': typeof OrgsOrgIdServersNodeIdServerIdAccessRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/activity': typeof OrgsOrgIdServersNodeIdServerIdActivityRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/backups': typeof OrgsOrgIdServersNodeIdServerIdBackupsRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/databases': typeof OrgsOrgIdServersNodeIdServerIdDatabasesRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/files': typeof OrgsOrgIdServersNodeIdServerIdFilesRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/network': typeof OrgsOrgIdServersNodeIdServerIdNetworkRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/schedules': typeof OrgsOrgIdServersNodeIdServerIdSchedulesRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/settings': typeof OrgsOrgIdServersNodeIdServerIdSettingsRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/startup': typeof OrgsOrgIdServersNodeIdServerIdStartupRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/': typeof OrgsOrgIdServersNodeIdServerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/settings/activity': typeof SettingsActivityRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/signin/link': typeof SigninLinkRoute
  '/signin/second-factor': typeof SigninSecondFactorRoute
  '/settings': typeof SettingsIndexRoute
  '/signin': typeof SigninIndexRoute
  '/orgs/$orgId/eggs': typeof OrgsOrgIdEggsRoute
  '/orgs/$orgId': typeof OrgsOrgIdIndexRoute
  '/orgs/$orgId/nodes/new': typeof OrgsOrgIdNodesNewRoute
  '/orgs/$orgId/servers/new': typeof OrgsOrgIdServersNewRoute
  '/orgs/$orgId/settings/activity': typeof OrgsOrgIdSettingsActivityRoute
  '/orgs/$orgId/settings/billing': typeof OrgsOrgIdSettingsBillingRoute
  '/orgs/$orgId/settings/members': typeof OrgsOrgIdSettingsMembersRoute
  '/orgs/$orgId/nodes': typeof OrgsOrgIdNodesIndexRoute
  '/orgs/$orgId/servers': typeof OrgsOrgIdServersIndexRoute
  '/orgs/$orgId/settings': typeof OrgsOrgIdSettingsIndexRoute
  '/orgs/$orgId/nodes/$nodeId/health': typeof OrgsOrgIdNodesNodeIdHealthRoute
  '/orgs/$orgId/nodes/$nodeId/settings': typeof OrgsOrgIdNodesNodeIdSettingsRoute
  '/orgs/$orgId/nodes/$nodeId': typeof OrgsOrgIdNodesNodeIdIndexRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/access': typeof OrgsOrgIdServersNodeIdServerIdAccessRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/activity': typeof OrgsOrgIdServersNodeIdServerIdActivityRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/backups': typeof OrgsOrgIdServersNodeIdServerIdBackupsRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/databases': typeof OrgsOrgIdServersNodeIdServerIdDatabasesRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/files': typeof OrgsOrgIdServersNodeIdServerIdFilesRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/network': typeof OrgsOrgIdServersNodeIdServerIdNetworkRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/schedules': typeof OrgsOrgIdServersNodeIdServerIdSchedulesRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/settings': typeof OrgsOrgIdServersNodeIdServerIdSettingsRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/startup': typeof OrgsOrgIdServersNodeIdServerIdStartupRoute
  '/orgs/$orgId/servers/$nodeId/$serverId': typeof OrgsOrgIdServersNodeIdServerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/settings': typeof SettingsRouteWithChildren
  '/orgs/$orgId': typeof OrgsOrgIdRouteWithChildren
  '/settings/activity': typeof SettingsActivityRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/signin/link': typeof SigninLinkRoute
  '/signin/second-factor': typeof SigninSecondFactorRoute
  '/settings/': typeof SettingsIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/orgs/$orgId/eggs': typeof OrgsOrgIdEggsRoute
  '/orgs/$orgId/settings': typeof OrgsOrgIdSettingsRouteWithChildren
  '/orgs/$orgId/': typeof OrgsOrgIdIndexRoute
  '/orgs/$orgId/nodes/$nodeId': typeof OrgsOrgIdNodesNodeIdRouteWithChildren
  '/orgs/$orgId/nodes/new': typeof OrgsOrgIdNodesNewRoute
  '/orgs/$orgId/servers/new': typeof OrgsOrgIdServersNewRoute
  '/orgs/$orgId/settings/activity': typeof OrgsOrgIdSettingsActivityRoute
  '/orgs/$orgId/settings/billing': typeof OrgsOrgIdSettingsBillingRoute
  '/orgs/$orgId/settings/members': typeof OrgsOrgIdSettingsMembersRoute
  '/orgs/$orgId/nodes/': typeof OrgsOrgIdNodesIndexRoute
  '/orgs/$orgId/servers/': typeof OrgsOrgIdServersIndexRoute
  '/orgs/$orgId/settings/': typeof OrgsOrgIdSettingsIndexRoute
  '/orgs/$orgId/nodes/$nodeId/health': typeof OrgsOrgIdNodesNodeIdHealthRoute
  '/orgs/$orgId/nodes/$nodeId/settings': typeof OrgsOrgIdNodesNodeIdSettingsRoute
  '/orgs/$orgId/servers/$nodeId/$serverId': typeof OrgsOrgIdServersNodeIdServerIdRouteWithChildren
  '/orgs/$orgId/nodes/$nodeId/': typeof OrgsOrgIdNodesNodeIdIndexRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/access': typeof OrgsOrgIdServersNodeIdServerIdAccessRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/activity': typeof OrgsOrgIdServersNodeIdServerIdActivityRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/backups': typeof OrgsOrgIdServersNodeIdServerIdBackupsRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/databases': typeof OrgsOrgIdServersNodeIdServerIdDatabasesRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/files': typeof OrgsOrgIdServersNodeIdServerIdFilesRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/network': typeof OrgsOrgIdServersNodeIdServerIdNetworkRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/schedules': typeof OrgsOrgIdServersNodeIdServerIdSchedulesRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/settings': typeof OrgsOrgIdServersNodeIdServerIdSettingsRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/startup': typeof OrgsOrgIdServersNodeIdServerIdStartupRoute
  '/orgs/$orgId/servers/$nodeId/$serverId/': typeof OrgsOrgIdServersNodeIdServerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invite'
    | '/settings'
    | '/orgs/$orgId'
    | '/settings/activity'
    | '/settings/security'
    | '/signin/link'
    | '/signin/second-factor'
    | '/settings/'
    | '/signin/'
    | '/orgs/$orgId/eggs'
    | '/orgs/$orgId/settings'
    | '/orgs/$orgId/'
    | '/orgs/$orgId/nodes/$nodeId'
    | '/orgs/$orgId/nodes/new'
    | '/orgs/$orgId/servers/new'
    | '/orgs/$orgId/settings/activity'
    | '/orgs/$orgId/settings/billing'
    | '/orgs/$orgId/settings/members'
    | '/orgs/$orgId/nodes/'
    | '/orgs/$orgId/servers/'
    | '/orgs/$orgId/settings/'
    | '/orgs/$orgId/nodes/$nodeId/health'
    | '/orgs/$orgId/nodes/$nodeId/settings'
    | '/orgs/$orgId/servers/$nodeId/$serverId'
    | '/orgs/$orgId/nodes/$nodeId/'
    | '/orgs/$orgId/servers/$nodeId/$serverId/access'
    | '/orgs/$orgId/servers/$nodeId/$serverId/activity'
    | '/orgs/$orgId/servers/$nodeId/$serverId/backups'
    | '/orgs/$orgId/servers/$nodeId/$serverId/databases'
    | '/orgs/$orgId/servers/$nodeId/$serverId/files'
    | '/orgs/$orgId/servers/$nodeId/$serverId/network'
    | '/orgs/$orgId/servers/$nodeId/$serverId/schedules'
    | '/orgs/$orgId/servers/$nodeId/$serverId/settings'
    | '/orgs/$orgId/servers/$nodeId/$serverId/startup'
    | '/orgs/$orgId/servers/$nodeId/$serverId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite'
    | '/settings/activity'
    | '/settings/security'
    | '/signin/link'
    | '/signin/second-factor'
    | '/settings'
    | '/signin'
    | '/orgs/$orgId/eggs'
    | '/orgs/$orgId'
    | '/orgs/$orgId/nodes/new'
    | '/orgs/$orgId/servers/new'
    | '/orgs/$orgId/settings/activity'
    | '/orgs/$orgId/settings/billing'
    | '/orgs/$orgId/settings/members'
    | '/orgs/$orgId/nodes'
    | '/orgs/$orgId/servers'
    | '/orgs/$orgId/settings'
    | '/orgs/$orgId/nodes/$nodeId/health'
    | '/orgs/$orgId/nodes/$nodeId/settings'
    | '/orgs/$orgId/nodes/$nodeId'
    | '/orgs/$orgId/servers/$nodeId/$serverId/access'
    | '/orgs/$orgId/servers/$nodeId/$serverId/activity'
    | '/orgs/$orgId/servers/$nodeId/$serverId/backups'
    | '/orgs/$orgId/servers/$nodeId/$serverId/databases'
    | '/orgs/$orgId/servers/$nodeId/$serverId/files'
    | '/orgs/$orgId/servers/$nodeId/$serverId/network'
    | '/orgs/$orgId/servers/$nodeId/$serverId/schedules'
    | '/orgs/$orgId/servers/$nodeId/$serverId/settings'
    | '/orgs/$orgId/servers/$nodeId/$serverId/startup'
    | '/orgs/$orgId/servers/$nodeId/$serverId'
  id:
    | '__root__'
    | '/'
    | '/invite'
    | '/settings'
    | '/orgs/$orgId'
    | '/settings/activity'
    | '/settings/security'
    | '/signin/link'
    | '/signin/second-factor'
    | '/settings/'
    | '/signin/'
    | '/orgs/$orgId/eggs'
    | '/orgs/$orgId/settings'
    | '/orgs/$orgId/'
    | '/orgs/$orgId/nodes/$nodeId'
    | '/orgs/$orgId/nodes/new'
    | '/orgs/$orgId/servers/new'
    | '/orgs/$orgId/settings/activity'
    | '/orgs/$orgId/settings/billing'
    | '/orgs/$orgId/settings/members'
    | '/orgs/$orgId/nodes/'
    | '/orgs/$orgId/servers/'
    | '/orgs/$orgId/settings/'
    | '/orgs/$orgId/nodes/$nodeId/health'
    | '/orgs/$orgId/nodes/$nodeId/settings'
    | '/orgs/$orgId/servers/$nodeId/$serverId'
    | '/orgs/$orgId/nodes/$nodeId/'
    | '/orgs/$orgId/servers/$nodeId/$serverId/access'
    | '/orgs/$orgId/servers/$nodeId/$serverId/activity'
    | '/orgs/$orgId/servers/$nodeId/$serverId/backups'
    | '/orgs/$orgId/servers/$nodeId/$serverId/databases'
    | '/orgs/$orgId/servers/$nodeId/$serverId/files'
    | '/orgs/$orgId/servers/$nodeId/$serverId/network'
    | '/orgs/$orgId/servers/$nodeId/$serverId/schedules'
    | '/orgs/$orgId/servers/$nodeId/$serverId/settings'
    | '/orgs/$orgId/servers/$nodeId/$serverId/startup'
    | '/orgs/$orgId/servers/$nodeId/$serverId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InviteRoute: typeof InviteRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  OrgsOrgIdRoute: typeof OrgsOrgIdRouteWithChildren
  SigninLinkRoute: typeof SigninLinkRoute
  SigninSecondFactorRoute: typeof SigninSecondFactorRoute
  SigninIndexRoute: typeof SigninIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$orgId': {
      id: '/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof OrgsOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/activity': {
      id: '/settings/activity'
      path: '/activity'
      fullPath: '/settings/activity'
      preLoaderRoute: typeof SettingsActivityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/signin/': {
      id: '/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof SigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/link': {
      id: '/signin/link'
      path: '/signin/link'
      fullPath: '/signin/link'
      preLoaderRoute: typeof SigninLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/second-factor': {
      id: '/signin/second-factor'
      path: '/signin/second-factor'
      fullPath: '/signin/second-factor'
      preLoaderRoute: typeof SigninSecondFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$orgId/': {
      id: '/orgs/$orgId/'
      path: '/'
      fullPath: '/orgs/$orgId/'
      preLoaderRoute: typeof OrgsOrgIdIndexRouteImport
      parentRoute: typeof OrgsOrgIdRoute
    }
    '/orgs/$orgId/eggs': {
      id: '/orgs/$orgId/eggs'
      path: '/eggs'
      fullPath: '/orgs/$orgId/eggs'
      preLoaderRoute: typeof OrgsOrgIdEggsRouteImport
      parentRoute: typeof OrgsOrgIdRoute
    }
    '/orgs/$orgId/settings': {
      id: '/orgs/$orgId/settings'
      path: '/settings'
      fullPath: '/orgs/$orgId/settings'
      preLoaderRoute: typeof OrgsOrgIdSettingsRouteImport
      parentRoute: typeof OrgsOrgIdRoute
    }
    '/orgs/$orgId/nodes/': {
      id: '/orgs/$orgId/nodes/'
      path: '/nodes'
      fullPath: '/orgs/$orgId/nodes/'
      preLoaderRoute: typeof OrgsOrgIdNodesIndexRouteImport
      parentRoute: typeof OrgsOrgIdRoute
    }
    '/orgs/$orgId/nodes/$nodeId': {
      id: '/orgs/$orgId/nodes/$nodeId'
      path: '/nodes/$nodeId'
      fullPath: '/orgs/$orgId/nodes/$nodeId'
      preLoaderRoute: typeof OrgsOrgIdNodesNodeIdRouteImport
      parentRoute: typeof OrgsOrgIdRoute
    }
    '/orgs/$orgId/nodes/new': {
      id: '/orgs/$orgId/nodes/new'
      path: '/nodes/new'
      fullPath: '/orgs/$orgId/nodes/new'
      preLoaderRoute: typeof OrgsOrgIdNodesNewRouteImport
      parentRoute: typeof OrgsOrgIdRoute
    }
    '/orgs/$orgId/servers/': {
      id: '/orgs/$orgId/servers/'
      path: '/servers'
      fullPath: '/orgs/$orgId/servers/'
      preLoaderRoute: typeof OrgsOrgIdServersIndexRouteImport
      parentRoute: typeof OrgsOrgIdRoute
    }
    '/orgs/$orgId/servers/new': {
      id: '/orgs/$orgId/servers/new'
      path: '/servers/new'
      fullPath: '/orgs/$orgId/servers/new'
      preLoaderRoute: typeof OrgsOrgIdServersNewRouteImport
      parentRoute: typeof OrgsOrgIdRoute
    }
    '/orgs/$orgId/settings/': {
      id: '/orgs/$orgId/settings/'
      path: '/'
      fullPath: '/orgs/$orgId/settings/'
      preLoaderRoute: typeof OrgsOrgIdSettingsIndexRouteImport
      parentRoute: typeof OrgsOrgIdSettingsRoute
    }
    '/orgs/$orgId/settings/activity': {
      id: '/orgs/$orgId/settings/activity'
      path: '/activity'
      fullPath: '/orgs/$orgId/settings/activity'
      preLoaderRoute: typeof OrgsOrgIdSettingsActivityRouteImport
      parentRoute: typeof OrgsOrgIdSettingsRoute
    }
    '/orgs/$orgId/settings/billing': {
      id: '/orgs/$orgId/settings/billing'
      path: '/billing'
      fullPath: '/orgs/$orgId/settings/billing'
      preLoaderRoute: typeof OrgsOrgIdSettingsBillingRouteImport
      parentRoute: typeof OrgsOrgIdSettingsRoute
    }
    '/orgs/$orgId/settings/members': {
      id: '/orgs/$orgId/settings/members'
      path: '/members'
      fullPath: '/orgs/$orgId/settings/members'
      preLoaderRoute: typeof OrgsOrgIdSettingsMembersRouteImport
      parentRoute: typeof OrgsOrgIdSettingsRoute
    }
    '/orgs/$orgId/nodes/$nodeId/': {
      id: '/orgs/$orgId/nodes/$nodeId/'
      path: '/'
      fullPath: '/orgs/$orgId/nodes/$nodeId/'
      preLoaderRoute: typeof OrgsOrgIdNodesNodeIdIndexRouteImport
      parentRoute: typeof OrgsOrgIdNodesNodeIdRoute
    }
    '/orgs/$orgId/nodes/$nodeId/health': {
      id: '/orgs/$orgId/nodes/$nodeId/health'
      path: '/health'
      fullPath: '/orgs/$orgId/nodes/$nodeId/health'
      preLoaderRoute: typeof OrgsOrgIdNodesNodeIdHealthRouteImport
      parentRoute: typeof OrgsOrgIdNodesNodeIdRoute
    }
    '/orgs/$orgId/nodes/$nodeId/settings': {
      id: '/orgs/$orgId/nodes/$nodeId/settings'
      path: '/settings'
      fullPath: '/orgs/$orgId/nodes/$nodeId/settings'
      preLoaderRoute: typeof OrgsOrgIdNodesNodeIdSettingsRouteImport
      parentRoute: typeof OrgsOrgIdNodesNodeIdRoute
    }
    '/orgs/$orgId/servers/$nodeId/$serverId': {
      id: '/orgs/$orgId/servers/$nodeId/$serverId'
      path: '/servers/$nodeId/$serverId'
      fullPath: '/orgs/$orgId/servers/$nodeId/$serverId'
      preLoaderRoute: typeof OrgsOrgIdServersNodeIdServerIdRouteImport
      parentRoute: typeof OrgsOrgIdRoute
    }
    '/orgs/$orgId/servers/$nodeId/$serverId/': {
      id: '/orgs/$orgId/servers/$nodeId/$serverId/'
      path: '/'
      fullPath: '/orgs/$orgId/servers/$nodeId/$serverId/'
      preLoaderRoute: typeof OrgsOrgIdServersNodeIdServerIdIndexRouteImport
      parentRoute: typeof OrgsOrgIdServersNodeIdServerIdRoute
    }
    '/orgs/$orgId/servers/$nodeId/$serverId/access': {
      id: '/orgs/$orgId/servers/$nodeId/$serverId/access'
      path: '/access'
      fullPath: '/orgs/$orgId/servers/$nodeId/$serverId/access'
      preLoaderRoute: typeof OrgsOrgIdServersNodeIdServerIdAccessRouteImport
      parentRoute: typeof OrgsOrgIdServersNodeIdServerIdRoute
    }
    '/orgs/$orgId/servers/$nodeId/$serverId/activity': {
      id: '/orgs/$orgId/servers/$nodeId/$serverId/activity'
      path: '/activity'
      fullPath: '/orgs/$orgId/servers/$nodeId/$serverId/activity'
      preLoaderRoute: typeof OrgsOrgIdServersNodeIdServerIdActivityRouteImport
      parentRoute: typeof OrgsOrgIdServersNodeIdServerIdRoute
    }
    '/orgs/$orgId/servers/$nodeId/$serverId/backups': {
      id: '/orgs/$orgId/servers/$nodeId/$serverId/backups'
      path: '/backups'
      fullPath: '/orgs/$orgId/servers/$nodeId/$serverId/backups'
      preLoaderRoute: typeof OrgsOrgIdServersNodeIdServerIdBackupsRouteImport
      parentRoute: typeof OrgsOrgIdServersNodeIdServerIdRoute
    }
    '/orgs/$orgId/servers/$nodeId/$serverId/databases': {
      id: '/orgs/$orgId/servers/$nodeId/$serverId/databases'
      path: '/databases'
      fullPath: '/orgs/$orgId/servers/$nodeId/$serverId/databases'
      preLoaderRoute: typeof OrgsOrgIdServersNodeIdServerIdDatabasesRouteImport
      parentRoute: typeof OrgsOrgIdServersNodeIdServerIdRoute
    }
    '/orgs/$orgId/servers/$nodeId/$serverId/files': {
      id: '/orgs/$orgId/servers/$nodeId/$serverId/files'
      path: '/files'
      fullPath: '/orgs/$orgId/servers/$nodeId/$serverId/files'
      preLoaderRoute: typeof OrgsOrgIdServersNodeIdServerIdFilesRouteImport
      parentRoute: typeof OrgsOrgIdServersNodeIdServerIdRoute
    }
    '/orgs/$orgId/servers/$nodeId/$serverId/network': {
      id: '/orgs/$orgId/servers/$nodeId/$serverId/network'
      path: '/network'
      fullPath: '/orgs/$orgId/servers/$nodeId/$serverId/network'
      preLoaderRoute: typeof OrgsOrgIdServersNodeIdServerIdNetworkRouteImport
      parentRoute: typeof OrgsOrgIdServersNodeIdServerIdRoute
    }
    '/orgs/$orgId/servers/$nodeId/$serverId/schedules': {
      id: '/orgs/$orgId/servers/$nodeId/$serverId/schedules'
      path: '/schedules'
      fullPath: '/orgs/$orgId/servers/$nodeId/$serverId/schedules'
      preLoaderRoute: typeof OrgsOrgIdServersNodeIdServerIdSchedulesRouteImport
      parentRoute: typeof OrgsOrgIdServersNodeIdServerIdRoute
    }
    '/orgs/$orgId/servers/$nodeId/$serverId/settings': {
      id: '/orgs/$orgId/servers/$nodeId/$serverId/settings'
      path: '/settings'
      fullPath: '/orgs/$orgId/servers/$nodeId/$serverId/settings'
      preLoaderRoute: typeof OrgsOrgIdServersNodeIdServerIdSettingsRouteImport
      parentRoute: typeof OrgsOrgIdServersNodeIdServerIdRoute
    }
    '/orgs/$orgId/servers/$nodeId/$serverId/startup': {
      id: '/orgs/$orgId/servers/$nodeId/$serverId/startup'
      path: '/startup'
      fullPath: '/orgs/$orgId/servers/$nodeId/$serverId/startup'
      preLoaderRoute: typeof OrgsOrgIdServersNodeIdServerIdStartupRouteImport
      parentRoute: typeof OrgsOrgIdServersNodeIdServerIdRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsActivityRoute: typeof SettingsActivityRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsActivityRoute: SettingsActivityRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface OrgsOrgIdSettingsRouteChildren {
  OrgsOrgIdSettingsActivityRoute: typeof OrgsOrgIdSettingsActivityRoute
  OrgsOrgIdSettingsBillingRoute: typeof OrgsOrgIdSettingsBillingRoute
  OrgsOrgIdSettingsMembersRoute: typeof OrgsOrgIdSettingsMembersRoute
  OrgsOrgIdSettingsIndexRoute: typeof OrgsOrgIdSettingsIndexRoute
}

const OrgsOrgIdSettingsRouteChildren: OrgsOrgIdSettingsRouteChildren = {
  OrgsOrgIdSettingsActivityRoute: OrgsOrgIdSettingsActivityRoute,
  OrgsOrgIdSettingsBillingRoute: OrgsOrgIdSettingsBillingRoute,
  OrgsOrgIdSettingsMembersRoute: OrgsOrgIdSettingsMembersRoute,
  OrgsOrgIdSettingsIndexRoute: OrgsOrgIdSettingsIndexRoute,
}

const OrgsOrgIdSettingsRouteWithChildren =
  OrgsOrgIdSettingsRoute._addFileChildren(OrgsOrgIdSettingsRouteChildren)

interface OrgsOrgIdNodesNodeIdRouteChildren {
  OrgsOrgIdNodesNodeIdHealthRoute: typeof OrgsOrgIdNodesNodeIdHealthRoute
  OrgsOrgIdNodesNodeIdSettingsRoute: typeof OrgsOrgIdNodesNodeIdSettingsRoute
  OrgsOrgIdNodesNodeIdIndexRoute: typeof OrgsOrgIdNodesNodeIdIndexRoute
}

const OrgsOrgIdNodesNodeIdRouteChildren: OrgsOrgIdNodesNodeIdRouteChildren = {
  OrgsOrgIdNodesNodeIdHealthRoute: OrgsOrgIdNodesNodeIdHealthRoute,
  OrgsOrgIdNodesNodeIdSettingsRoute: OrgsOrgIdNodesNodeIdSettingsRoute,
  OrgsOrgIdNodesNodeIdIndexRoute: OrgsOrgIdNodesNodeIdIndexRoute,
}

const OrgsOrgIdNodesNodeIdRouteWithChildren =
  OrgsOrgIdNodesNodeIdRoute._addFileChildren(OrgsOrgIdNodesNodeIdRouteChildren)

interface OrgsOrgIdServersNodeIdServerIdRouteChildren {
  OrgsOrgIdServersNodeIdServerIdAccessRoute: typeof OrgsOrgIdServersNodeIdServerIdAccessRoute
  OrgsOrgIdServersNodeIdServerIdActivityRoute: typeof OrgsOrgIdServersNodeIdServerIdActivityRoute
  OrgsOrgIdServersNodeIdServerIdBackupsRoute: typeof OrgsOrgIdServersNodeIdServerIdBackupsRoute
  OrgsOrgIdServersNodeIdServerIdDatabasesRoute: typeof OrgsOrgIdServersNodeIdServerIdDatabasesRoute
  OrgsOrgIdServersNodeIdServerIdFilesRoute: typeof OrgsOrgIdServersNodeIdServerIdFilesRoute
  OrgsOrgIdServersNodeIdServerIdNetworkRoute: typeof OrgsOrgIdServersNodeIdServerIdNetworkRoute
  OrgsOrgIdServersNodeIdServerIdSchedulesRoute: typeof OrgsOrgIdServersNodeIdServerIdSchedulesRoute
  OrgsOrgIdServersNodeIdServerIdSettingsRoute: typeof OrgsOrgIdServersNodeIdServerIdSettingsRoute
  OrgsOrgIdServersNodeIdServerIdStartupRoute: typeof OrgsOrgIdServersNodeIdServerIdStartupRoute
  OrgsOrgIdServersNodeIdServerIdIndexRoute: typeof OrgsOrgIdServersNodeIdServerIdIndexRoute
}

const OrgsOrgIdServersNodeIdServerIdRouteChildren: OrgsOrgIdServersNodeIdServerIdRouteChildren =
  {
    OrgsOrgIdServersNodeIdServerIdAccessRoute:
      OrgsOrgIdServersNodeIdServerIdAccessRoute,
    OrgsOrgIdServersNodeIdServerIdActivityRoute:
      OrgsOrgIdServersNodeIdServerIdActivityRoute,
    OrgsOrgIdServersNodeIdServerIdBackupsRoute:
      OrgsOrgIdServersNodeIdServerIdBackupsRoute,
    OrgsOrgIdServersNodeIdServerIdDatabasesRoute:
      OrgsOrgIdServersNodeIdServerIdDatabasesRoute,
    OrgsOrgIdServersNodeIdServerIdFilesRoute:
      OrgsOrgIdServersNodeIdServerIdFilesRoute,
    OrgsOrgIdServersNodeIdServerIdNetworkRoute:
      OrgsOrgIdServersNodeIdServerIdNetworkRoute,
    OrgsOrgIdServersNodeIdServerIdSchedulesRoute:
      OrgsOrgIdServersNodeIdServerIdSchedulesRoute,
    OrgsOrgIdServersNodeIdServerIdSettingsRoute:
      OrgsOrgIdServersNodeIdServerIdSettingsRoute,
    OrgsOrgIdServersNodeIdServerIdStartupRoute:
      OrgsOrgIdServersNodeIdServerIdStartupRoute,
    OrgsOrgIdServersNodeIdServerIdIndexRoute:
      OrgsOrgIdServersNodeIdServerIdIndexRoute,
  }

const OrgsOrgIdServersNodeIdServerIdRouteWithChildren =
  OrgsOrgIdServersNodeIdServerIdRoute._addFileChildren(
    OrgsOrgIdServersNodeIdServerIdRouteChildren,
  )

interface OrgsOrgIdRouteChildren {
  OrgsOrgIdEggsRoute: typeof OrgsOrgIdEggsRoute
  OrgsOrgIdSettingsRoute: typeof OrgsOrgIdSettingsRouteWithChildren
  OrgsOrgIdIndexRoute: typeof OrgsOrgIdIndexRoute
  OrgsOrgIdNodesNodeIdRoute: typeof OrgsOrgIdNodesNodeIdRouteWithChildren
  OrgsOrgIdNodesNewRoute: typeof OrgsOrgIdNodesNewRoute
  OrgsOrgIdServersNewRoute: typeof OrgsOrgIdServersNewRoute
  OrgsOrgIdNodesIndexRoute: typeof OrgsOrgIdNodesIndexRoute
  OrgsOrgIdServersIndexRoute: typeof OrgsOrgIdServersIndexRoute
  OrgsOrgIdServersNodeIdServerIdRoute: typeof OrgsOrgIdServersNodeIdServerIdRouteWithChildren
}

const OrgsOrgIdRouteChildren: OrgsOrgIdRouteChildren = {
  OrgsOrgIdEggsRoute: OrgsOrgIdEggsRoute,
  OrgsOrgIdSettingsRoute: OrgsOrgIdSettingsRouteWithChildren,
  OrgsOrgIdIndexRoute: OrgsOrgIdIndexRoute,
  OrgsOrgIdNodesNodeIdRoute: OrgsOrgIdNodesNodeIdRouteWithChildren,
  OrgsOrgIdNodesNewRoute: OrgsOrgIdNodesNewRoute,
  OrgsOrgIdServersNewRoute: OrgsOrgIdServersNewRoute,
  OrgsOrgIdNodesIndexRoute: OrgsOrgIdNodesIndexRoute,
  OrgsOrgIdServersIndexRoute: OrgsOrgIdServersIndexRoute,
  OrgsOrgIdServersNodeIdServerIdRoute:
    OrgsOrgIdServersNodeIdServerIdRouteWithChildren,
}

const OrgsOrgIdRouteWithChildren = OrgsOrgIdRoute._addFileChildren(
  OrgsOrgIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InviteRoute: InviteRoute,
  SettingsRoute: SettingsRouteWithChildren,
  OrgsOrgIdRoute: OrgsOrgIdRouteWithChildren,
  SigninLinkRoute: SigninLinkRoute,
  SigninSecondFactorRoute: SigninSecondFactorRoute,
  SigninIndexRoute: SigninIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
